/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TransactionListResponseDto } from "../TransactionListResponseDto";

export type TransactionsControllerListQuery = {
	/**
	 * @description Formato YYYY-MM
	 * @example 2026-03
	 * @type string | undefined
	 */
	month?: string;
};

export type TransactionsControllerListStatus200 = TransactionListResponseDto;

export type TransactionsControllerListStatus400 = unknown;

export type TransactionsControllerListOptions = {
	body?: never;
	path?: never;
	query?: TransactionsControllerListQuery;
	headers?: never;
};

export type TransactionsControllerListResponses = {
	"200": TransactionsControllerListStatus200;
	"400": TransactionsControllerListStatus400;
};

/**
 * @description Union of all possible responses
 */
export type TransactionsControllerListResponse =
	TransactionsControllerListStatus200;
