/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TransactionResponseDto } from "../TransactionResponseDto";

export type TransactionsControllerGetByIdPath = {
	id: string;
};

export type TransactionsControllerGetByIdStatus200 = TransactionResponseDto;

export type TransactionsControllerGetByIdStatus404 = unknown;

export type TransactionsControllerGetByIdOptions = {
	body?: never;
	path: TransactionsControllerGetByIdPath;
	query?: never;
	headers?: never;
};

export type TransactionsControllerGetByIdResponses = {
	"200": TransactionsControllerGetByIdStatus200;
	"404": TransactionsControllerGetByIdStatus404;
};

/**
 * @description Union of all possible responses
 */
export type TransactionsControllerGetByIdResponse =
	TransactionsControllerGetByIdStatus200;
