/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MessageResponseDto } from "../message-response-dto.ts";

export type TransactionsControllerRemovePathParams = {
	/**
	 * @type string
	 */
	id: string;
};

export type TransactionsControllerRemove200 = MessageResponseDto;

export type TransactionsControllerRemoveMutationResponse =
	TransactionsControllerRemove200;

export type TransactionsControllerRemoveMutation = {
	Response: TransactionsControllerRemove200;
	PathParams: TransactionsControllerRemovePathParams;
	Errors: any;
};
