/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type TransactionsControllerListMonths200 = string[];

export type TransactionsControllerListMonthsQueryResponse =
	TransactionsControllerListMonths200;

export type TransactionsControllerListMonthsQuery = {
	Response: TransactionsControllerListMonths200;
	Errors: any;
};
