/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TransactionListResponseDto } from "../transaction-list-response-dto.ts";

export type TransactionsControllerListQueryParams = {
	/**
	 * @description Formato YYYY-MM
	 * @type string | undefined
	 */
	month?: string;
};

export type TransactionsControllerList200 = TransactionListResponseDto;

/**
 * @description Formato de mês inválido (YYYY-MM)
 */
export type TransactionsControllerList400 = any;

export type TransactionsControllerListQueryResponse =
	TransactionsControllerList200;

export type TransactionsControllerListQuery = {
	Response: TransactionsControllerList200;
	QueryParams: TransactionsControllerListQueryParams;
	Errors: TransactionsControllerList400;
};
