/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateTransactionDto } from "../CreateTransactionDto";
import type { TransactionListResponseDto } from "../TransactionListResponseDto";

export type TransactionsControllerCreateHeaders = {
	/**
	 * @description Opcional. Reenviar a mesma chave devolve o resultado da primeira criação em vez de duplicar (usado pela fila offline do app).
	 * @type string | undefined
	 */
	"idempotency-key"?: string;
};

export type TransactionsControllerCreateStatus201 = TransactionListResponseDto;

export type TransactionsControllerCreateStatus404 = unknown;

export type TransactionsControllerCreateBody = CreateTransactionDto;

export type TransactionsControllerCreateOptions = {
	body: TransactionsControllerCreateBody;
	path?: never;
	query?: never;
	headers?: TransactionsControllerCreateHeaders;
};

export type TransactionsControllerCreateResponses = {
	"201": TransactionsControllerCreateStatus201;
	"404": TransactionsControllerCreateStatus404;
};

/**
 * @description Union of all possible responses
 */
export type TransactionsControllerCreateResponse =
	TransactionsControllerCreateStatus201;
