/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TransactionResponseDto } from "../transaction-response-dto.ts";

export type TransactionsControllerGetByIdPathParams = {
	/**
	 * @type string
	 */
	id: string;
};

/**
 * @description Transação encontrada
 */
export type TransactionsControllerGetById200 = TransactionResponseDto;

/**
 * @description Transação não encontrada
 */
export type TransactionsControllerGetById404 = any;

export type TransactionsControllerGetByIdQueryResponse =
	TransactionsControllerGetById200;

export type TransactionsControllerGetByIdQuery = {
	Response: TransactionsControllerGetById200;
	PathParams: TransactionsControllerGetByIdPathParams;
	Errors: TransactionsControllerGetById404;
};
