/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type TransactionsControllerListMonthsStatus200 = string[];

export type TransactionsControllerListMonthsOptions = {
	body?: never;
	path?: never;
	query?: never;
	headers?: never;
};

export type TransactionsControllerListMonthsResponses = {
	"200": TransactionsControllerListMonthsStatus200;
};

/**
 * @description Union of all possible responses
 */
export type TransactionsControllerListMonthsResponse =
	TransactionsControllerListMonthsStatus200;
