/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TransactionResponseDto } from "../TransactionResponseDto";
import type { UpdateTransactionDto } from "../UpdateTransactionDto";

export type TransactionsControllerUpdatePath = {
	id: string;
};

export type TransactionsControllerUpdateStatus200 = TransactionResponseDto;

export type TransactionsControllerUpdateStatus404 = unknown;

export type TransactionsControllerUpdateBody = UpdateTransactionDto;

export type TransactionsControllerUpdateOptions = {
	body: TransactionsControllerUpdateBody;
	path: TransactionsControllerUpdatePath;
	query?: never;
	headers?: never;
};

export type TransactionsControllerUpdateResponses = {
	"200": TransactionsControllerUpdateStatus200;
	"404": TransactionsControllerUpdateStatus404;
};

/**
 * @description Union of all possible responses
 */
export type TransactionsControllerUpdateResponse =
	TransactionsControllerUpdateStatus200;
