/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MessageResponseDto } from "../MessageResponseDto";

export type TransactionsControllerRemovePath = {
	id: string;
};

export type TransactionsControllerRemoveStatus200 = MessageResponseDto;

export type TransactionsControllerRemoveOptions = {
	body?: never;
	path: TransactionsControllerRemovePath;
	query?: never;
	headers?: never;
};

export type TransactionsControllerRemoveResponses = {
	"200": TransactionsControllerRemoveStatus200;
};

/**
 * @description Union of all possible responses
 */
export type TransactionsControllerRemoveResponse =
	TransactionsControllerRemoveStatus200;
