/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MessageResponseDto } from "../MessageResponseDto";

export type BudgetsControllerRemovePath = {
	id: string;
};

export type BudgetsControllerRemoveStatus200 = MessageResponseDto;

export type BudgetsControllerRemoveStatus409 = unknown;

export type BudgetsControllerRemoveOptions = {
	body?: never;
	path: BudgetsControllerRemovePath;
	query?: never;
	headers?: never;
};

export type BudgetsControllerRemoveResponses = {
	"200": BudgetsControllerRemoveStatus200;
	"409": BudgetsControllerRemoveStatus409;
};

/**
 * @description Union of all possible responses
 */
export type BudgetsControllerRemoveResponse = BudgetsControllerRemoveStatus200;
