/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BudgetResponseDto } from "../BudgetResponseDto";
import type { CreateBudgetDto } from "../CreateBudgetDto";

export type BudgetsControllerCreateStatus201 = BudgetResponseDto;

export type BudgetsControllerCreateStatus404 = unknown;

export type BudgetsControllerCreateStatus409 = unknown;

export type BudgetsControllerCreateBody = CreateBudgetDto;

export type BudgetsControllerCreateOptions = {
	body: BudgetsControllerCreateBody;
	path?: never;
	query?: never;
	headers?: never;
};

export type BudgetsControllerCreateResponses = {
	"201": BudgetsControllerCreateStatus201;
	"404": BudgetsControllerCreateStatus404;
	"409": BudgetsControllerCreateStatus409;
};

/**
 * @description Union of all possible responses
 */
export type BudgetsControllerCreateResponse = BudgetsControllerCreateStatus201;
