/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BudgetResponseDto } from "../BudgetResponseDto";

export type BudgetsControllerListQuery = {
	/**
	 * @description Formato YYYY-MM
	 * @example 2026-03
	 * @type string | undefined
	 */
	month?: string;
};

export type BudgetsControllerListStatus200 = BudgetResponseDto[];

export type BudgetsControllerListOptions = {
	body?: never;
	path?: never;
	query?: BudgetsControllerListQuery;
	headers?: never;
};

export type BudgetsControllerListResponses = {
	"200": BudgetsControllerListStatus200;
};

/**
 * @description Union of all possible responses
 */
export type BudgetsControllerListResponse = BudgetsControllerListStatus200;
