/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BudgetResponseDto } from "../budget-response-dto.ts";

export type BudgetsControllerListQueryParams = {
	/**
	 * @description Formato YYYY-MM
	 * @type string | undefined
	 */
	month?: string;
};

export type BudgetsControllerList200 = BudgetResponseDto[];

export type BudgetsControllerListQueryResponse = BudgetsControllerList200;

export type BudgetsControllerListQuery = {
	Response: BudgetsControllerList200;
	QueryParams: BudgetsControllerListQueryParams;
	Errors: any;
};
