/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MessageResponseDto } from "../message-response-dto.ts";

export type BudgetsControllerRemovePathParams = {
	/**
	 * @type string
	 */
	id: string;
};

export type BudgetsControllerRemove200 = MessageResponseDto;

export type BudgetsControllerRemoveMutationResponse =
	BudgetsControllerRemove200;

export type BudgetsControllerRemoveMutation = {
	Response: BudgetsControllerRemove200;
	PathParams: BudgetsControllerRemovePathParams;
	Errors: any;
};
