/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BudgetResponseDto } from "../BudgetResponseDto";
import type { UpdateBudgetDto } from "../UpdateBudgetDto";

export type BudgetsControllerUpdatePath = {
	id: string;
};

export type BudgetsControllerUpdateStatus200 = BudgetResponseDto;

export type BudgetsControllerUpdateBody = UpdateBudgetDto;

export type BudgetsControllerUpdateOptions = {
	body: BudgetsControllerUpdateBody;
	path: BudgetsControllerUpdatePath;
	query?: never;
	headers?: never;
};

export type BudgetsControllerUpdateResponses = {
	"200": BudgetsControllerUpdateStatus200;
};

/**
 * @description Union of all possible responses
 */
export type BudgetsControllerUpdateResponse = BudgetsControllerUpdateStatus200;
