/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ReplicateBudgetsDto } from "../ReplicateBudgetsDto";
import type { ReplicateBudgetsResponseDto } from "../ReplicateBudgetsResponseDto";

export type BudgetsControllerReplicateStatus200 = ReplicateBudgetsResponseDto;

export type BudgetsControllerReplicateBody = ReplicateBudgetsDto;

export type BudgetsControllerReplicateOptions = {
	body: BudgetsControllerReplicateBody;
	path?: never;
	query?: never;
	headers?: never;
};

export type BudgetsControllerReplicateResponses = {
	"200": BudgetsControllerReplicateStatus200;
};

/**
 * @description Union of all possible responses
 */
export type BudgetsControllerReplicateResponse =
	BudgetsControllerReplicateStatus200;
