/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ReplicateBudgetsDto } from "../replicate-budgets-dto.ts";
import type { ReplicateBudgetsResponseDto } from "../replicate-budgets-response-dto.ts";

/**
 * @description Orçamentos replicados
 */
export type BudgetsControllerReplicate200 = ReplicateBudgetsResponseDto;

export type BudgetsControllerReplicateMutationRequest = ReplicateBudgetsDto;

export type BudgetsControllerReplicateMutationResponse =
	BudgetsControllerReplicate200;

export type BudgetsControllerReplicateMutation = {
	Response: BudgetsControllerReplicate200;
	Request: BudgetsControllerReplicateMutationRequest;
	Errors: any;
};
