/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BudgetResponseDto } from "../budget-response-dto.ts";

export type BudgetsControllerGetByIdPathParams = {
	/**
	 * @type string
	 */
	id: string;
};

/**
 * @description Orçamento encontrado
 */
export type BudgetsControllerGetById200 = BudgetResponseDto;

/**
 * @description Orçamento não encontrado
 */
export type BudgetsControllerGetById404 = any;

export type BudgetsControllerGetByIdQueryResponse = BudgetsControllerGetById200;

export type BudgetsControllerGetByIdQuery = {
	Response: BudgetsControllerGetById200;
	PathParams: BudgetsControllerGetByIdPathParams;
	Errors: BudgetsControllerGetById404;
};
