/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BudgetResponseDto } from "../BudgetResponseDto";

export type BudgetsControllerGetByIdPath = {
	id: string;
};

export type BudgetsControllerGetByIdStatus200 = BudgetResponseDto;

export type BudgetsControllerGetByIdStatus404 = unknown;

export type BudgetsControllerGetByIdOptions = {
	body?: never;
	path: BudgetsControllerGetByIdPath;
	query?: never;
	headers?: never;
};

export type BudgetsControllerGetByIdResponses = {
	"200": BudgetsControllerGetByIdStatus200;
	"404": BudgetsControllerGetByIdStatus404;
};

/**
 * @description Union of all possible responses
 */
export type BudgetsControllerGetByIdResponse =
	BudgetsControllerGetByIdStatus200;
