/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BudgetProgressResponseDto } from "../BudgetProgressResponseDto";

export type BudgetsControllerProgressPath = {
	id: string;
};

export type BudgetsControllerProgressStatus200 = BudgetProgressResponseDto;

export type BudgetsControllerProgressOptions = {
	body?: never;
	path: BudgetsControllerProgressPath;
	query?: never;
	headers?: never;
};

export type BudgetsControllerProgressResponses = {
	"200": BudgetsControllerProgressStatus200;
};

/**
 * @description Union of all possible responses
 */
export type BudgetsControllerProgressResponse =
	BudgetsControllerProgressStatus200;
