/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	TransactionsControllerListMonthsOptions,
	TransactionsControllerListMonthsResponses,
} from "../schemas/transactions/TransactionsControllerListMonths";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/transactions/months}
 */
export function transactionsControllerListMonths<
	ThrowOnError extends boolean = true,
>(
	options: Options<TransactionsControllerListMonthsOptions, ThrowOnError> = {},
): Promise<
	UnwrappedResult<TransactionsControllerListMonthsResponses, ThrowOnError>
> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "GET",
			url: "/v1/transactions/months",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<TransactionsControllerListMonthsResponses, ThrowOnError>
	>;
}
