/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	TransactionsControllerUpdateOptions,
	TransactionsControllerUpdateResponses,
} from "../schemas/transactions/TransactionsControllerUpdate";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/transactions/:id}
 */
export function transactionsControllerUpdate<
	ThrowOnError extends boolean = true,
>(
	options: Options<TransactionsControllerUpdateOptions, ThrowOnError>,
): Promise<
	UnwrappedResult<TransactionsControllerUpdateResponses, ThrowOnError>
> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "PUT",
			url: "/v1/transactions/{id}",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<TransactionsControllerUpdateResponses, ThrowOnError>
	>;
}
