/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	TransactionsControllerRemoveOptions,
	TransactionsControllerRemoveResponses,
} from "../schemas/transactions/TransactionsControllerRemove";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/transactions/:id}
 */
export function transactionsControllerRemove<
	ThrowOnError extends boolean = true,
>(
	options: Options<TransactionsControllerRemoveOptions, ThrowOnError>,
): Promise<
	UnwrappedResult<TransactionsControllerRemoveResponses, ThrowOnError>
> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "DELETE",
			url: "/v1/transactions/{id}",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<TransactionsControllerRemoveResponses, ThrowOnError>
	>;
}
