/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	TransactionsControllerCreateOptions,
	TransactionsControllerCreateResponses,
} from "../schemas/transactions/TransactionsControllerCreate";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/transactions}
 */
export function transactionsControllerCreate<
	ThrowOnError extends boolean = true,
>(
	options: Options<TransactionsControllerCreateOptions, ThrowOnError>,
): Promise<
	UnwrappedResult<TransactionsControllerCreateResponses, ThrowOnError>
> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "POST",
			url: "/v1/transactions",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<TransactionsControllerCreateResponses, ThrowOnError>
	>;
}
