/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	TransactionsControllerListOptions,
	TransactionsControllerListResponses,
} from "../schemas/transactions/TransactionsControllerList";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/transactions}
 */
export function transactionsControllerList<ThrowOnError extends boolean = true>(
	options: Options<TransactionsControllerListOptions, ThrowOnError> = {},
): Promise<UnwrappedResult<TransactionsControllerListResponses, ThrowOnError>> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "GET",
			url: "/v1/transactions",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<TransactionsControllerListResponses, ThrowOnError>
	>;
}
