/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MessageResponseDto } from "../message-response-dto.ts";

export type AttachmentsControllerRemovePathParams = {
	/**
	 * @type string
	 */
	id: string;
};

export type AttachmentsControllerRemove200 = MessageResponseDto;

/**
 * @description Anexo não encontrado
 */
export type AttachmentsControllerRemove404 = any;

export type AttachmentsControllerRemoveMutationResponse =
	AttachmentsControllerRemove200;

export type AttachmentsControllerRemoveMutation = {
	Response: AttachmentsControllerRemoveMutationResponse;
	PathParams: AttachmentsControllerRemovePathParams;
	Errors: AttachmentsControllerRemove404;
};
