/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AttachmentsControllerGetContentPath = {
	id: string;
};

export type AttachmentsControllerGetContentStatus200 = unknown;

export type AttachmentsControllerGetContentStatus404 = unknown;

export type AttachmentsControllerGetContentOptions = {
	body?: never;
	path: AttachmentsControllerGetContentPath;
	query?: never;
	headers?: never;
};

export type AttachmentsControllerGetContentResponses = {
	"200": AttachmentsControllerGetContentStatus200;
	"404": AttachmentsControllerGetContentStatus404;
};

/**
 * @description Union of all possible responses
 */
export type AttachmentsControllerGetContentResponse =
	AttachmentsControllerGetContentStatus200;
