/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AttachmentDownloadResponseDto } from "../attachment-download-response-dto.ts";

export type AttachmentsControllerGetDownloadUrlPathParams = {
	/**
	 * @type string
	 */
	id: string;
};

export type AttachmentsControllerGetDownloadUrl200 =
	AttachmentDownloadResponseDto;

/**
 * @description Anexo não encontrado
 */
export type AttachmentsControllerGetDownloadUrl404 = any;

export type AttachmentsControllerGetDownloadUrlQueryResponse =
	AttachmentsControllerGetDownloadUrl200;

export type AttachmentsControllerGetDownloadUrlQuery = {
	Response: AttachmentsControllerGetDownloadUrlQueryResponse;
	PathParams: AttachmentsControllerGetDownloadUrlPathParams;
	Errors: AttachmentsControllerGetDownloadUrl404;
};
