/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AttachmentDownloadResponseDto } from "../AttachmentDownloadResponseDto";

export type AttachmentsControllerGetDownloadUrlPath = {
	id: string;
};

export type AttachmentsControllerGetDownloadUrlStatus200 =
	AttachmentDownloadResponseDto;

export type AttachmentsControllerGetDownloadUrlStatus404 = unknown;

export type AttachmentsControllerGetDownloadUrlOptions = {
	body?: never;
	path: AttachmentsControllerGetDownloadUrlPath;
	query?: never;
	headers?: never;
};

export type AttachmentsControllerGetDownloadUrlResponses = {
	"200": AttachmentsControllerGetDownloadUrlStatus200;
	"404": AttachmentsControllerGetDownloadUrlStatus404;
};

/**
 * @description Union of all possible responses
 */
export type AttachmentsControllerGetDownloadUrlResponse =
	AttachmentsControllerGetDownloadUrlStatus200;
