/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MessageResponseDto } from "../MessageResponseDto";

export type AttachmentsControllerRemovePath = {
	id: string;
};

export type AttachmentsControllerRemoveStatus200 = MessageResponseDto;

export type AttachmentsControllerRemoveStatus404 = unknown;

export type AttachmentsControllerRemoveOptions = {
	body?: never;
	path: AttachmentsControllerRemovePath;
	query?: never;
	headers?: never;
};

export type AttachmentsControllerRemoveResponses = {
	"200": AttachmentsControllerRemoveStatus200;
	"404": AttachmentsControllerRemoveStatus404;
};

/**
 * @description Union of all possible responses
 */
export type AttachmentsControllerRemoveResponse =
	AttachmentsControllerRemoveStatus200;
