/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AttachmentResponseDto } from "../AttachmentResponseDto";

export type TransactionAttachmentsControllerUploadPath = {
	transactionId: string;
};

export type TransactionAttachmentsControllerUploadStatus201 =
	AttachmentResponseDto;

export type TransactionAttachmentsControllerUploadStatus400 = unknown;

export type TransactionAttachmentsControllerUploadStatus404 = unknown;

export type TransactionAttachmentsControllerUploadBody = {
	file: Blob;
};

export type TransactionAttachmentsControllerUploadOptions = {
	body: TransactionAttachmentsControllerUploadBody;
	path: TransactionAttachmentsControllerUploadPath;
	query?: never;
	headers?: never;
};

export type TransactionAttachmentsControllerUploadResponses = {
	"201": TransactionAttachmentsControllerUploadStatus201;
	"400": TransactionAttachmentsControllerUploadStatus400;
	"404": TransactionAttachmentsControllerUploadStatus404;
};

/**
 * @description Union of all possible responses
 */
export type TransactionAttachmentsControllerUploadResponse =
	TransactionAttachmentsControllerUploadStatus201;
