/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AttachmentResponseDto } from "../attachment-response-dto.ts";

export type TransactionAttachmentsControllerListPathParams = {
	/**
	 * @type string
	 */
	transactionId: string;
};

export type TransactionAttachmentsControllerList200 = AttachmentResponseDto[];

/**
 * @description Transação não encontrada
 */
export type TransactionAttachmentsControllerList404 = any;

export type TransactionAttachmentsControllerListQueryResponse =
	TransactionAttachmentsControllerList200;

export type TransactionAttachmentsControllerListQuery = {
	Response: TransactionAttachmentsControllerListQueryResponse;
	PathParams: TransactionAttachmentsControllerListPathParams;
	Errors: TransactionAttachmentsControllerList404;
};
