/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AttachmentResponseDto } from "../attachment-response-dto.ts";

export type TransactionAttachmentsControllerUploadPathParams = {
	/**
	 * @type string
	 */
	transactionId: string;
};

export type TransactionAttachmentsControllerUpload201 = AttachmentResponseDto;

/**
 * @description Arquivo inválido ou maior que o limite
 */
export type TransactionAttachmentsControllerUpload400 = any;

/**
 * @description Transação não encontrada
 */
export type TransactionAttachmentsControllerUpload404 = any;

export type TransactionAttachmentsControllerUploadMutationRequest = {
	/**
	 * @type string, binary
	 */
	file: Blob;
};

export type TransactionAttachmentsControllerUploadMutationResponse =
	TransactionAttachmentsControllerUpload201;

export type TransactionAttachmentsControllerUploadMutation = {
	Response: TransactionAttachmentsControllerUploadMutationResponse;
	Request: TransactionAttachmentsControllerUploadMutationRequest;
	PathParams: TransactionAttachmentsControllerUploadPathParams;
	Errors:
		| TransactionAttachmentsControllerUpload400
		| TransactionAttachmentsControllerUpload404;
};
