/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AttachmentResponseDto } from "../AttachmentResponseDto";

export type TransactionAttachmentsControllerListPath = {
	transactionId: string;
};

export type TransactionAttachmentsControllerListStatus200 =
	AttachmentResponseDto[];

export type TransactionAttachmentsControllerListStatus404 = unknown;

export type TransactionAttachmentsControllerListOptions = {
	body?: never;
	path: TransactionAttachmentsControllerListPath;
	query?: never;
	headers?: never;
};

export type TransactionAttachmentsControllerListResponses = {
	"200": TransactionAttachmentsControllerListStatus200;
	"404": TransactionAttachmentsControllerListStatus404;
};

/**
 * @description Union of all possible responses
 */
export type TransactionAttachmentsControllerListResponse =
	TransactionAttachmentsControllerListStatus200;
