/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	TransactionsControllerGetByIdOptions,
	TransactionsControllerGetByIdStatus200,
	TransactionsControllerGetByIdStatus404,
} from "../../schemas/transactions/TransactionsControllerGetById";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { transactionsControllerGetById } from "../transactionsControllerGetById";

export const transactionsControllerGetByIdQueryKey = ({
	path,
}: Omit<TransactionsControllerGetByIdOptions, "headers">) =>
	[{ url: "/v1/transactions/:id", params: path }] as const;

type TransactionsControllerGetByIdQueryKey = ReturnType<
	typeof transactionsControllerGetByIdQueryKey
>;

export function transactionsControllerGetByIdQueryOptions(
	{ path }: TransactionsControllerGetByIdOptions,
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const queryKey = transactionsControllerGetByIdQueryKey({ path });
	return queryOptions<
		TransactionsControllerGetByIdStatus200,
		ResponseErrorConfig<TransactionsControllerGetByIdStatus404>,
		TransactionsControllerGetByIdStatus200,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return await transactionsControllerGetById({
				...config,
				path,
				signal: config.signal ?? signal,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/transactions/:id}
 */
export function useTransactionsControllerGetById<
	TData = TransactionsControllerGetByIdStatus200,
	TQueryData = TransactionsControllerGetByIdStatus200,
	TQueryKey extends QueryKey = TransactionsControllerGetByIdQueryKey,
>(
	{
		path,
	}: {
		path:
			| TransactionsControllerGetByIdOptions["path"]
			| (() => TransactionsControllerGetByIdOptions["path"]);
	},
	options: {
		query?: Partial<
			QueryObserverOptions<
				TransactionsControllerGetByIdStatus200,
				ResponseErrorConfig<TransactionsControllerGetByIdStatus404>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const resolvedParams = { path: typeof path === "function" ? path() : path };
	const queryKey =
		resolvedOptions?.queryKey ??
		transactionsControllerGetByIdQueryKey(resolvedParams);

	const queryResult = useQuery(
		{
			...transactionsControllerGetByIdQueryOptions(resolvedParams, config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<
		TData,
		ResponseErrorConfig<TransactionsControllerGetByIdStatus404>
	> & { queryKey: TQueryKey };

	queryResult.queryKey = queryKey as TQueryKey;

	return queryResult;
}
