/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	TransactionsControllerCreateOptions,
	TransactionsControllerCreateStatus201,
	TransactionsControllerCreateStatus404,
} from "../../schemas/transactions/TransactionsControllerCreate";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { transactionsControllerCreate } from "../transactionsControllerCreate";

export const transactionsControllerCreateMutationKey = () =>
	[{ url: "/v1/transactions" }] as const;

export function transactionsControllerCreateMutationOptions<TContext = unknown>(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const mutationKey = transactionsControllerCreateMutationKey();
	return mutationOptions<
		TransactionsControllerCreateStatus201,
		ResponseErrorConfig<TransactionsControllerCreateStatus404>,
		TransactionsControllerCreateOptions,
		TContext
	>({
		mutationKey,
		mutationFn: async ({ body, headers }) => {
			return await transactionsControllerCreate({
				...config,
				body,
				headers,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/transactions}
 */
export function useTransactionsControllerCreate<TContext>(
	options: {
		mutation?: UseMutationOptions<
			TransactionsControllerCreateStatus201,
			ResponseErrorConfig<TransactionsControllerCreateStatus404>,
			TransactionsControllerCreateOptions,
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? transactionsControllerCreateMutationKey();

	const baseOptions = transactionsControllerCreateMutationOptions(
		config,
	) as UseMutationOptions<
		TransactionsControllerCreateStatus201,
		ResponseErrorConfig<TransactionsControllerCreateStatus404>,
		TransactionsControllerCreateOptions,
		TContext
	>;

	return useMutation<
		TransactionsControllerCreateStatus201,
		ResponseErrorConfig<TransactionsControllerCreateStatus404>,
		TransactionsControllerCreateOptions,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		TransactionsControllerCreateStatus201,
		ResponseErrorConfig<TransactionsControllerCreateStatus404>,
		TransactionsControllerCreateOptions,
		TContext
	>;
}
