/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	TransactionsControllerUpdateOptions,
	TransactionsControllerUpdateStatus200,
	TransactionsControllerUpdateStatus404,
} from "../../schemas/transactions/TransactionsControllerUpdate";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { transactionsControllerUpdate } from "../transactionsControllerUpdate";

export const transactionsControllerUpdateMutationKey = () =>
	[{ url: "/v1/transactions/:id" }] as const;

export function transactionsControllerUpdateMutationOptions<TContext = unknown>(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const mutationKey = transactionsControllerUpdateMutationKey();
	return mutationOptions<
		TransactionsControllerUpdateStatus200,
		ResponseErrorConfig<TransactionsControllerUpdateStatus404>,
		TransactionsControllerUpdateOptions,
		TContext
	>({
		mutationKey,
		mutationFn: async ({ path, body }) => {
			return await transactionsControllerUpdate({
				...config,
				path,
				body,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/transactions/:id}
 */
export function useTransactionsControllerUpdate<TContext>(
	options: {
		mutation?: UseMutationOptions<
			TransactionsControllerUpdateStatus200,
			ResponseErrorConfig<TransactionsControllerUpdateStatus404>,
			TransactionsControllerUpdateOptions,
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? transactionsControllerUpdateMutationKey();

	const baseOptions = transactionsControllerUpdateMutationOptions(
		config,
	) as UseMutationOptions<
		TransactionsControllerUpdateStatus200,
		ResponseErrorConfig<TransactionsControllerUpdateStatus404>,
		TransactionsControllerUpdateOptions,
		TContext
	>;

	return useMutation<
		TransactionsControllerUpdateStatus200,
		ResponseErrorConfig<TransactionsControllerUpdateStatus404>,
		TransactionsControllerUpdateOptions,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		TransactionsControllerUpdateStatus200,
		ResponseErrorConfig<TransactionsControllerUpdateStatus404>,
		TransactionsControllerUpdateOptions,
		TContext
	>;
}
