/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type { TransactionsControllerListMonthsStatus200 } from "../../schemas/transactions/TransactionsControllerListMonths";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { transactionsControllerListMonths } from "../transactionsControllerListMonths";

export const transactionsControllerListMonthsQueryKey = () =>
	[{ url: "/v1/transactions/months" }] as const;

type TransactionsControllerListMonthsQueryKey = ReturnType<
	typeof transactionsControllerListMonthsQueryKey
>;

export function transactionsControllerListMonthsQueryOptions(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const queryKey = transactionsControllerListMonthsQueryKey();
	return queryOptions<
		TransactionsControllerListMonthsStatus200,
		ResponseErrorConfig<Error>,
		TransactionsControllerListMonthsStatus200,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return await transactionsControllerListMonths({
				...config,
				signal: config.signal ?? signal,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/transactions/months}
 */
export function useTransactionsControllerListMonths<
	TData = TransactionsControllerListMonthsStatus200,
	TQueryData = TransactionsControllerListMonthsStatus200,
	TQueryKey extends QueryKey = TransactionsControllerListMonthsQueryKey,
>(
	options: {
		query?: Partial<
			QueryObserverOptions<
				TransactionsControllerListMonthsStatus200,
				ResponseErrorConfig<Error>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey =
		resolvedOptions?.queryKey ?? transactionsControllerListMonthsQueryKey();

	const queryResult = useQuery(
		{
			...transactionsControllerListMonthsQueryOptions(config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
		queryKey: TQueryKey;
	};

	queryResult.queryKey = queryKey as TQueryKey;

	return queryResult;
}
