/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	TransactionsControllerRemoveOptions,
	TransactionsControllerRemoveStatus200,
} from "../../schemas/transactions/TransactionsControllerRemove";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { transactionsControllerRemove } from "../transactionsControllerRemove";

export const transactionsControllerRemoveMutationKey = () =>
	[{ url: "/v1/transactions/:id" }] as const;

export function transactionsControllerRemoveMutationOptions<TContext = unknown>(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const mutationKey = transactionsControllerRemoveMutationKey();
	return mutationOptions<
		TransactionsControllerRemoveStatus200,
		ResponseErrorConfig<Error>,
		TransactionsControllerRemoveOptions,
		TContext
	>({
		mutationKey,
		mutationFn: async ({ path }) => {
			return await transactionsControllerRemove({
				...config,
				path,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/transactions/:id}
 */
export function useTransactionsControllerRemove<TContext>(
	options: {
		mutation?: UseMutationOptions<
			TransactionsControllerRemoveStatus200,
			ResponseErrorConfig<Error>,
			TransactionsControllerRemoveOptions,
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? transactionsControllerRemoveMutationKey();

	const baseOptions = transactionsControllerRemoveMutationOptions(
		config,
	) as UseMutationOptions<
		TransactionsControllerRemoveStatus200,
		ResponseErrorConfig<Error>,
		TransactionsControllerRemoveOptions,
		TContext
	>;

	return useMutation<
		TransactionsControllerRemoveStatus200,
		ResponseErrorConfig<Error>,
		TransactionsControllerRemoveOptions,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		TransactionsControllerRemoveStatus200,
		ResponseErrorConfig<Error>,
		TransactionsControllerRemoveOptions,
		TContext
	>;
}
