/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	TransactionsControllerListOptions,
	TransactionsControllerListStatus200,
	TransactionsControllerListStatus400,
} from "../../schemas/transactions/TransactionsControllerList";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { transactionsControllerList } from "../transactionsControllerList";

export const transactionsControllerListQueryKey = ({
	query,
}: Omit<TransactionsControllerListOptions, "headers"> = {}) =>
	[{ url: "/v1/transactions" }, ...(query ? [query] : [])] as const;

type TransactionsControllerListQueryKey = ReturnType<
	typeof transactionsControllerListQueryKey
>;

export function transactionsControllerListQueryOptions(
	{ query }: TransactionsControllerListOptions = {},
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const queryKey = transactionsControllerListQueryKey({ query });
	return queryOptions<
		TransactionsControllerListStatus200,
		ResponseErrorConfig<TransactionsControllerListStatus400>,
		TransactionsControllerListStatus200,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return await transactionsControllerList({
				...config,
				query,
				signal: config.signal ?? signal,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/transactions}
 */
export function useTransactionsControllerList<
	TData = TransactionsControllerListStatus200,
	TQueryData = TransactionsControllerListStatus200,
	TQueryKey extends QueryKey = TransactionsControllerListQueryKey,
>(
	{
		query,
	}: {
		query?:
			| TransactionsControllerListOptions["query"]
			| (() => TransactionsControllerListOptions["query"]);
	} = {},
	options: {
		query?: Partial<
			QueryObserverOptions<
				TransactionsControllerListStatus200,
				ResponseErrorConfig<TransactionsControllerListStatus400>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const resolvedParams = {
		query: typeof query === "function" ? query() : query,
	};
	const queryKey =
		resolvedOptions?.queryKey ??
		transactionsControllerListQueryKey(resolvedParams);

	const queryResult = useQuery(
		{
			...transactionsControllerListQueryOptions(resolvedParams, config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<
		TData,
		ResponseErrorConfig<TransactionsControllerListStatus400>
	> & { queryKey: TQueryKey };

	queryResult.queryKey = queryKey as TQueryKey;

	return queryResult;
}
