/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	DashboardControllerGetSummaryOptions,
	DashboardControllerGetSummaryStatus200,
	DashboardControllerGetSummaryStatus400,
	DashboardControllerGetSummaryStatus401,
} from "../../schemas/dashboard/DashboardControllerGetSummary";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { dashboardControllerGetSummary } from "../dashboardControllerGetSummary";

export const dashboardControllerGetSummaryQueryKey = ({
	query,
}: Omit<DashboardControllerGetSummaryOptions, "headers"> = {}) =>
	[{ url: "/v1/dashboard" }, ...(query ? [query] : [])] as const;

type DashboardControllerGetSummaryQueryKey = ReturnType<
	typeof dashboardControllerGetSummaryQueryKey
>;

export function dashboardControllerGetSummaryQueryOptions(
	{ query }: DashboardControllerGetSummaryOptions = {},
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const queryKey = dashboardControllerGetSummaryQueryKey({ query });
	return queryOptions<
		DashboardControllerGetSummaryStatus200,
		ResponseErrorConfig<
			| DashboardControllerGetSummaryStatus400
			| DashboardControllerGetSummaryStatus401
		>,
		DashboardControllerGetSummaryStatus200,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return await dashboardControllerGetSummary({
				...config,
				query,
				signal: config.signal ?? signal,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/dashboard}
 */
export function useDashboardControllerGetSummary<
	TData = DashboardControllerGetSummaryStatus200,
	TQueryData = DashboardControllerGetSummaryStatus200,
	TQueryKey extends QueryKey = DashboardControllerGetSummaryQueryKey,
>(
	{
		query,
	}: {
		query?:
			| DashboardControllerGetSummaryOptions["query"]
			| (() => DashboardControllerGetSummaryOptions["query"]);
	} = {},
	options: {
		query?: Partial<
			QueryObserverOptions<
				DashboardControllerGetSummaryStatus200,
				ResponseErrorConfig<
					| DashboardControllerGetSummaryStatus400
					| DashboardControllerGetSummaryStatus401
				>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const resolvedParams = {
		query: typeof query === "function" ? query() : query,
	};
	const queryKey =
		resolvedOptions?.queryKey ??
		dashboardControllerGetSummaryQueryKey(resolvedParams);

	const queryResult = useQuery(
		{
			...dashboardControllerGetSummaryQueryOptions(resolvedParams, config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<
		TData,
		ResponseErrorConfig<
			| DashboardControllerGetSummaryStatus400
			| DashboardControllerGetSummaryStatus401
		>
	> & { queryKey: TQueryKey };

	queryResult.queryKey = queryKey as TQueryKey;

	return queryResult;
}
