/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type {
	TransactionAttachmentsControllerListQueryResponse,
	TransactionAttachmentsControllerListPathParams,
	TransactionAttachmentsControllerList404,
} from "../../schemas/attachments/transaction-attachments-controller-list.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { transactionAttachmentsControllerList } from "../transaction-attachments-controller-list.ts";

export const transactionAttachmentsControllerListQueryKey = (
	transactionId: TransactionAttachmentsControllerListPathParams["transactionId"],
) =>
	[
		{
			url: "/v1/transactions/:transactionId/attachments",
			params: { transactionId: transactionId },
		},
	] as const;

export type TransactionAttachmentsControllerListQueryKey = ReturnType<
	typeof transactionAttachmentsControllerListQueryKey
>;

export function useTransactionAttachmentsControllerListQueryOptions(
	transactionId: TransactionAttachmentsControllerListPathParams["transactionId"],
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = transactionAttachmentsControllerListQueryKey(transactionId);
	return queryOptions<
		TransactionAttachmentsControllerListQueryResponse,
		ResponseErrorConfig<TransactionAttachmentsControllerList404>,
		TransactionAttachmentsControllerListQueryResponse,
		typeof queryKey
	>({
		enabled: !!transactionId,
		queryKey,
		queryFn: async ({ signal }) => {
			return transactionAttachmentsControllerList(transactionId, {
				...config,
				signal: config.signal ?? signal,
			});
		},
	});
}

/**
 * {@link /v1/transactions/:transactionId/attachments}
 */
export function useTransactionAttachmentsControllerList<
	TData = TransactionAttachmentsControllerListQueryResponse,
	TQueryData = TransactionAttachmentsControllerListQueryResponse,
	TQueryKey extends QueryKey = TransactionAttachmentsControllerListQueryKey,
>(
	transactionId: TransactionAttachmentsControllerListPathParams["transactionId"],
	options: {
		query?: Partial<
			QueryObserverOptions<
				TransactionAttachmentsControllerListQueryResponse,
				ResponseErrorConfig<TransactionAttachmentsControllerList404>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey =
		resolvedOptions?.queryKey ??
		transactionAttachmentsControllerListQueryKey(transactionId);

	const query = useQuery(
		{
			...useTransactionAttachmentsControllerListQueryOptions(
				transactionId,
				config,
			),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<
		TData,
		ResponseErrorConfig<TransactionAttachmentsControllerList404>
	> & { queryKey: TQueryKey };

	query.queryKey = queryKey as TQueryKey;

	return query;
}
