/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type {
	TransactionAttachmentsControllerUploadMutationResponse,
	TransactionAttachmentsControllerUploadPathParams,
	TransactionAttachmentsControllerUpload400,
	TransactionAttachmentsControllerUpload404,
} from "../../schemas/attachments/transaction-attachments-controller-upload.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { transactionAttachmentsControllerUpload } from "../transaction-attachments-controller-upload.ts";

export const transactionAttachmentsControllerUploadMutationKey = () =>
	[{ url: "/v1/transactions/:transactionId/attachments" }] as const;

export type TransactionAttachmentsControllerUploadMutationKey = ReturnType<
	typeof transactionAttachmentsControllerUploadMutationKey
>;

type TransactionAttachmentsControllerUploadVariables = {
	transactionId: TransactionAttachmentsControllerUploadPathParams["transactionId"];
	data: FormData;
};

export function useTransactionAttachmentsControllerUploadMutationOptions<
	TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
	const mutationKey = transactionAttachmentsControllerUploadMutationKey();
	return mutationOptions<
		TransactionAttachmentsControllerUploadMutationResponse,
		ResponseErrorConfig<
			| TransactionAttachmentsControllerUpload400
			| TransactionAttachmentsControllerUpload404
		>,
		TransactionAttachmentsControllerUploadVariables,
		TContext
	>({
		mutationKey,
		mutationFn: async ({ transactionId, data }) => {
			return transactionAttachmentsControllerUpload(transactionId, data, config);
		},
	});
}

/**
 * {@link /v1/transactions/:transactionId/attachments}
 */
export function useTransactionAttachmentsControllerUpload<TContext>(
	options: {
		mutation?: UseMutationOptions<
			TransactionAttachmentsControllerUploadMutationResponse,
			ResponseErrorConfig<
				| TransactionAttachmentsControllerUpload400
				| TransactionAttachmentsControllerUpload404
			>,
			TransactionAttachmentsControllerUploadVariables,
			TContext
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ??
		transactionAttachmentsControllerUploadMutationKey();

	const baseOptions = useTransactionAttachmentsControllerUploadMutationOptions(
		config,
	) as UseMutationOptions<
		TransactionAttachmentsControllerUploadMutationResponse,
		ResponseErrorConfig<
			| TransactionAttachmentsControllerUpload400
			| TransactionAttachmentsControllerUpload404
		>,
		TransactionAttachmentsControllerUploadVariables,
		TContext
	>;

	return useMutation<
		TransactionAttachmentsControllerUploadMutationResponse,
		ResponseErrorConfig<
			| TransactionAttachmentsControllerUpload400
			| TransactionAttachmentsControllerUpload404
		>,
		TransactionAttachmentsControllerUploadVariables,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		TransactionAttachmentsControllerUploadMutationResponse,
		ResponseErrorConfig<
			| TransactionAttachmentsControllerUpload400
			| TransactionAttachmentsControllerUpload404
		>,
		TransactionAttachmentsControllerUploadVariables,
		TContext
	>;
}
