/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type {
	AttachmentsControllerGetDownloadUrlQueryResponse,
	AttachmentsControllerGetDownloadUrlPathParams,
	AttachmentsControllerGetDownloadUrl404,
} from "../../schemas/attachments/attachments-controller-get-download-url.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { attachmentsControllerGetDownloadUrl } from "../attachments-controller-get-download-url.ts";

export const attachmentsControllerGetDownloadUrlQueryKey = (
	id: AttachmentsControllerGetDownloadUrlPathParams["id"],
) => [{ url: "/v1/attachments/:id/download", params: { id: id } }] as const;

export type AttachmentsControllerGetDownloadUrlQueryKey = ReturnType<
	typeof attachmentsControllerGetDownloadUrlQueryKey
>;

export function useAttachmentsControllerGetDownloadUrlQueryOptions(
	id: AttachmentsControllerGetDownloadUrlPathParams["id"],
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = attachmentsControllerGetDownloadUrlQueryKey(id);
	return queryOptions<
		AttachmentsControllerGetDownloadUrlQueryResponse,
		ResponseErrorConfig<AttachmentsControllerGetDownloadUrl404>,
		AttachmentsControllerGetDownloadUrlQueryResponse,
		typeof queryKey
	>({
		enabled: !!id,
		queryKey,
		queryFn: async ({ signal }) => {
			return attachmentsControllerGetDownloadUrl(id, {
				...config,
				signal: config.signal ?? signal,
			});
		},
	});
}

/**
 * {@link /v1/attachments/:id/download}
 */
export function useAttachmentsControllerGetDownloadUrl<
	TData = AttachmentsControllerGetDownloadUrlQueryResponse,
	TQueryData = AttachmentsControllerGetDownloadUrlQueryResponse,
	TQueryKey extends QueryKey = AttachmentsControllerGetDownloadUrlQueryKey,
>(
	id: AttachmentsControllerGetDownloadUrlPathParams["id"],
	options: {
		query?: Partial<
			QueryObserverOptions<
				AttachmentsControllerGetDownloadUrlQueryResponse,
				ResponseErrorConfig<AttachmentsControllerGetDownloadUrl404>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey =
		resolvedOptions?.queryKey ?? attachmentsControllerGetDownloadUrlQueryKey(id);

	const query = useQuery(
		{
			...useAttachmentsControllerGetDownloadUrlQueryOptions(id, config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<
		TData,
		ResponseErrorConfig<AttachmentsControllerGetDownloadUrl404>
	> & { queryKey: TQueryKey };

	query.queryKey = queryKey as TQueryKey;

	return query;
}
