/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type {
	AttachmentsControllerRemoveMutationResponse,
	AttachmentsControllerRemovePathParams,
	AttachmentsControllerRemove404,
} from "../../schemas/attachments/attachments-controller-remove.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { attachmentsControllerRemove } from "../attachments-controller-remove.ts";

export const attachmentsControllerRemoveMutationKey = () =>
	[{ url: "/v1/attachments/:id" }] as const;

export type AttachmentsControllerRemoveMutationKey = ReturnType<
	typeof attachmentsControllerRemoveMutationKey
>;

export function useAttachmentsControllerRemoveMutationOptions<
	TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
	const mutationKey = attachmentsControllerRemoveMutationKey();
	return mutationOptions<
		AttachmentsControllerRemoveMutationResponse,
		ResponseErrorConfig<AttachmentsControllerRemove404>,
		{ id: AttachmentsControllerRemovePathParams["id"] },
		TContext
	>({
		mutationKey,
		mutationFn: async ({ id }) => {
			return attachmentsControllerRemove(id, config);
		},
	});
}

/**
 * {@link /v1/attachments/:id}
 */
export function useAttachmentsControllerRemove<TContext>(
	options: {
		mutation?: UseMutationOptions<
			AttachmentsControllerRemoveMutationResponse,
			ResponseErrorConfig<AttachmentsControllerRemove404>,
			{ id: AttachmentsControllerRemovePathParams["id"] },
			TContext
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? attachmentsControllerRemoveMutationKey();

	const baseOptions = useAttachmentsControllerRemoveMutationOptions(
		config,
	) as UseMutationOptions<
		AttachmentsControllerRemoveMutationResponse,
		ResponseErrorConfig<AttachmentsControllerRemove404>,
		{ id: AttachmentsControllerRemovePathParams["id"] },
		TContext
	>;

	return useMutation<
		AttachmentsControllerRemoveMutationResponse,
		ResponseErrorConfig<AttachmentsControllerRemove404>,
		{ id: AttachmentsControllerRemovePathParams["id"] },
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		AttachmentsControllerRemoveMutationResponse,
		ResponseErrorConfig<AttachmentsControllerRemove404>,
		{ id: AttachmentsControllerRemovePathParams["id"] },
		TContext
	>;
}
