/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	AttachmentsControllerRemoveOptions,
	AttachmentsControllerRemoveStatus200,
	AttachmentsControllerRemoveStatus404,
} from "../../schemas/attachments/AttachmentsControllerRemove";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { attachmentsControllerRemove } from "../attachmentsControllerRemove";

export const attachmentsControllerRemoveMutationKey = () =>
	[{ url: "/v1/attachments/:id" }] as const;

export function attachmentsControllerRemoveMutationOptions<TContext = unknown>(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const mutationKey = attachmentsControllerRemoveMutationKey();
	return mutationOptions<
		AttachmentsControllerRemoveStatus200,
		ResponseErrorConfig<AttachmentsControllerRemoveStatus404>,
		AttachmentsControllerRemoveOptions,
		TContext
	>({
		mutationKey,
		mutationFn: async ({ path }) => {
			return await attachmentsControllerRemove({
				...config,
				path,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/attachments/:id}
 */
export function useAttachmentsControllerRemove<TContext>(
	options: {
		mutation?: UseMutationOptions<
			AttachmentsControllerRemoveStatus200,
			ResponseErrorConfig<AttachmentsControllerRemoveStatus404>,
			AttachmentsControllerRemoveOptions,
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? attachmentsControllerRemoveMutationKey();

	const baseOptions = attachmentsControllerRemoveMutationOptions(
		config,
	) as UseMutationOptions<
		AttachmentsControllerRemoveStatus200,
		ResponseErrorConfig<AttachmentsControllerRemoveStatus404>,
		AttachmentsControllerRemoveOptions,
		TContext
	>;

	return useMutation<
		AttachmentsControllerRemoveStatus200,
		ResponseErrorConfig<AttachmentsControllerRemoveStatus404>,
		AttachmentsControllerRemoveOptions,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		AttachmentsControllerRemoveStatus200,
		ResponseErrorConfig<AttachmentsControllerRemoveStatus404>,
		AttachmentsControllerRemoveOptions,
		TContext
	>;
}
