/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	AttachmentsControllerGetDownloadUrlOptions,
	AttachmentsControllerGetDownloadUrlStatus200,
	AttachmentsControllerGetDownloadUrlStatus404,
} from "../../schemas/attachments/AttachmentsControllerGetDownloadUrl";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { attachmentsControllerGetDownloadUrl } from "../attachmentsControllerGetDownloadUrl";

export const attachmentsControllerGetDownloadUrlQueryKey = ({
	path,
}: Omit<AttachmentsControllerGetDownloadUrlOptions, "headers">) =>
	[{ url: "/v1/attachments/:id/download", params: path }] as const;

type AttachmentsControllerGetDownloadUrlQueryKey = ReturnType<
	typeof attachmentsControllerGetDownloadUrlQueryKey
>;

export function attachmentsControllerGetDownloadUrlQueryOptions(
	{ path }: AttachmentsControllerGetDownloadUrlOptions,
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const queryKey = attachmentsControllerGetDownloadUrlQueryKey({ path });
	return queryOptions<
		AttachmentsControllerGetDownloadUrlStatus200,
		ResponseErrorConfig<AttachmentsControllerGetDownloadUrlStatus404>,
		AttachmentsControllerGetDownloadUrlStatus200,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return await attachmentsControllerGetDownloadUrl({
				...config,
				path,
				signal: config.signal ?? signal,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/attachments/:id/download}
 */
export function useAttachmentsControllerGetDownloadUrl<
	TData = AttachmentsControllerGetDownloadUrlStatus200,
	TQueryData = AttachmentsControllerGetDownloadUrlStatus200,
	TQueryKey extends QueryKey = AttachmentsControllerGetDownloadUrlQueryKey,
>(
	{
		path,
	}: {
		path:
			| AttachmentsControllerGetDownloadUrlOptions["path"]
			| (() => AttachmentsControllerGetDownloadUrlOptions["path"]);
	},
	options: {
		query?: Partial<
			QueryObserverOptions<
				AttachmentsControllerGetDownloadUrlStatus200,
				ResponseErrorConfig<AttachmentsControllerGetDownloadUrlStatus404>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const resolvedParams = { path: typeof path === "function" ? path() : path };
	const queryKey =
		resolvedOptions?.queryKey ??
		attachmentsControllerGetDownloadUrlQueryKey(resolvedParams);

	const queryResult = useQuery(
		{
			...attachmentsControllerGetDownloadUrlQueryOptions(
				resolvedParams,
				config,
			),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<
		TData,
		ResponseErrorConfig<AttachmentsControllerGetDownloadUrlStatus404>
	> & { queryKey: TQueryKey };

	queryResult.queryKey = queryKey as TQueryKey;

	return queryResult;
}
