/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	AttachmentsControllerGetContentOptions,
	AttachmentsControllerGetContentStatus200,
	AttachmentsControllerGetContentStatus404,
} from "../../schemas/attachments/AttachmentsControllerGetContent";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { attachmentsControllerGetContent } from "../attachmentsControllerGetContent";

export const attachmentsControllerGetContentQueryKey = ({
	path,
}: Omit<AttachmentsControllerGetContentOptions, "headers">) =>
	[{ url: "/v1/attachments/:id/content", params: path }] as const;

type AttachmentsControllerGetContentQueryKey = ReturnType<
	typeof attachmentsControllerGetContentQueryKey
>;

export function attachmentsControllerGetContentQueryOptions(
	{ path }: AttachmentsControllerGetContentOptions,
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const queryKey = attachmentsControllerGetContentQueryKey({ path });
	return queryOptions<
		AttachmentsControllerGetContentStatus200,
		ResponseErrorConfig<AttachmentsControllerGetContentStatus404>,
		AttachmentsControllerGetContentStatus200,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return await attachmentsControllerGetContent({
				...config,
				path,
				signal: config.signal ?? signal,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/attachments/:id/content}
 */
export function useAttachmentsControllerGetContent<
	TData = AttachmentsControllerGetContentStatus200,
	TQueryData = AttachmentsControllerGetContentStatus200,
	TQueryKey extends QueryKey = AttachmentsControllerGetContentQueryKey,
>(
	{
		path,
	}: {
		path:
			| AttachmentsControllerGetContentOptions["path"]
			| (() => AttachmentsControllerGetContentOptions["path"]);
	},
	options: {
		query?: Partial<
			QueryObserverOptions<
				AttachmentsControllerGetContentStatus200,
				ResponseErrorConfig<AttachmentsControllerGetContentStatus404>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const resolvedParams = { path: typeof path === "function" ? path() : path };
	const queryKey =
		resolvedOptions?.queryKey ??
		attachmentsControllerGetContentQueryKey(resolvedParams);

	const queryResult = useQuery(
		{
			...attachmentsControllerGetContentQueryOptions(resolvedParams, config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<
		TData,
		ResponseErrorConfig<AttachmentsControllerGetContentStatus404>
	> & { queryKey: TQueryKey };

	queryResult.queryKey = queryKey as TQueryKey;

	return queryResult;
}
