/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	TransactionAttachmentsControllerUploadOptions,
	TransactionAttachmentsControllerUploadStatus201,
	TransactionAttachmentsControllerUploadStatus400,
	TransactionAttachmentsControllerUploadStatus404,
} from "../../schemas/attachments/TransactionAttachmentsControllerUpload";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { transactionAttachmentsControllerUpload } from "../transactionAttachmentsControllerUpload";

export const transactionAttachmentsControllerUploadMutationKey = () =>
	[{ url: "/v1/transactions/:transactionId/attachments" }] as const;

export function transactionAttachmentsControllerUploadMutationOptions<
	TContext = unknown,
>(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const mutationKey = transactionAttachmentsControllerUploadMutationKey();
	return mutationOptions<
		TransactionAttachmentsControllerUploadStatus201,
		ResponseErrorConfig<
			| TransactionAttachmentsControllerUploadStatus400
			| TransactionAttachmentsControllerUploadStatus404
		>,
		TransactionAttachmentsControllerUploadOptions,
		TContext
	>({
		mutationKey,
		mutationFn: async ({ path, body }) => {
			return await transactionAttachmentsControllerUpload({
				...config,
				path,
				body,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/transactions/:transactionId/attachments}
 */
export function useTransactionAttachmentsControllerUpload<TContext>(
	options: {
		mutation?: UseMutationOptions<
			TransactionAttachmentsControllerUploadStatus201,
			ResponseErrorConfig<
				| TransactionAttachmentsControllerUploadStatus400
				| TransactionAttachmentsControllerUploadStatus404
			>,
			TransactionAttachmentsControllerUploadOptions,
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ??
		transactionAttachmentsControllerUploadMutationKey();

	const baseOptions = transactionAttachmentsControllerUploadMutationOptions(
		config,
	) as UseMutationOptions<
		TransactionAttachmentsControllerUploadStatus201,
		ResponseErrorConfig<
			| TransactionAttachmentsControllerUploadStatus400
			| TransactionAttachmentsControllerUploadStatus404
		>,
		TransactionAttachmentsControllerUploadOptions,
		TContext
	>;

	return useMutation<
		TransactionAttachmentsControllerUploadStatus201,
		ResponseErrorConfig<
			| TransactionAttachmentsControllerUploadStatus400
			| TransactionAttachmentsControllerUploadStatus404
		>,
		TransactionAttachmentsControllerUploadOptions,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		TransactionAttachmentsControllerUploadStatus201,
		ResponseErrorConfig<
			| TransactionAttachmentsControllerUploadStatus400
			| TransactionAttachmentsControllerUploadStatus404
		>,
		TransactionAttachmentsControllerUploadOptions,
		TContext
	>;
}
