/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	TransactionAttachmentsControllerListOptions,
	TransactionAttachmentsControllerListStatus200,
	TransactionAttachmentsControllerListStatus404,
} from "../../schemas/attachments/TransactionAttachmentsControllerList";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { transactionAttachmentsControllerList } from "../transactionAttachmentsControllerList";

export const transactionAttachmentsControllerListQueryKey = ({
	path,
}: Omit<TransactionAttachmentsControllerListOptions, "headers">) =>
	[
		{ url: "/v1/transactions/:transactionId/attachments", params: path },
	] as const;

type TransactionAttachmentsControllerListQueryKey = ReturnType<
	typeof transactionAttachmentsControllerListQueryKey
>;

export function transactionAttachmentsControllerListQueryOptions(
	{ path }: TransactionAttachmentsControllerListOptions,
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const queryKey = transactionAttachmentsControllerListQueryKey({ path });
	return queryOptions<
		TransactionAttachmentsControllerListStatus200,
		ResponseErrorConfig<TransactionAttachmentsControllerListStatus404>,
		TransactionAttachmentsControllerListStatus200,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return await transactionAttachmentsControllerList({
				...config,
				path,
				signal: config.signal ?? signal,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/transactions/:transactionId/attachments}
 */
export function useTransactionAttachmentsControllerList<
	TData = TransactionAttachmentsControllerListStatus200,
	TQueryData = TransactionAttachmentsControllerListStatus200,
	TQueryKey extends QueryKey = TransactionAttachmentsControllerListQueryKey,
>(
	{
		path,
	}: {
		path:
			| TransactionAttachmentsControllerListOptions["path"]
			| (() => TransactionAttachmentsControllerListOptions["path"]);
	},
	options: {
		query?: Partial<
			QueryObserverOptions<
				TransactionAttachmentsControllerListStatus200,
				ResponseErrorConfig<TransactionAttachmentsControllerListStatus404>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const resolvedParams = { path: typeof path === "function" ? path() : path };
	const queryKey =
		resolvedOptions?.queryKey ??
		transactionAttachmentsControllerListQueryKey(resolvedParams);

	const queryResult = useQuery(
		{
			...transactionAttachmentsControllerListQueryOptions(
				resolvedParams,
				config,
			),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<
		TData,
		ResponseErrorConfig<TransactionAttachmentsControllerListStatus404>
	> & { queryKey: TQueryKey };

	queryResult.queryKey = queryKey as TQueryKey;

	return queryResult;
}
