/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	CategoriesControllerCreateOptions,
	CategoriesControllerCreateStatus201,
	CategoriesControllerCreateStatus401,
	CategoriesControllerCreateStatus403,
	CategoriesControllerCreateStatus409,
} from "../../schemas/categories/CategoriesControllerCreate";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { categoriesControllerCreate } from "../categoriesControllerCreate";

export const categoriesControllerCreateMutationKey = () =>
	[{ url: "/v1/categories" }] as const;

export function categoriesControllerCreateMutationOptions<TContext = unknown>(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const mutationKey = categoriesControllerCreateMutationKey();
	return mutationOptions<
		CategoriesControllerCreateStatus201,
		ResponseErrorConfig<
			| CategoriesControllerCreateStatus401
			| CategoriesControllerCreateStatus403
			| CategoriesControllerCreateStatus409
		>,
		CategoriesControllerCreateOptions,
		TContext
	>({
		mutationKey,
		mutationFn: async ({ body }) => {
			return await categoriesControllerCreate({
				...config,
				body,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/categories}
 */
export function useCategoriesControllerCreate<TContext>(
	options: {
		mutation?: UseMutationOptions<
			CategoriesControllerCreateStatus201,
			ResponseErrorConfig<
				| CategoriesControllerCreateStatus401
				| CategoriesControllerCreateStatus403
				| CategoriesControllerCreateStatus409
			>,
			CategoriesControllerCreateOptions,
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? categoriesControllerCreateMutationKey();

	const baseOptions = categoriesControllerCreateMutationOptions(
		config,
	) as UseMutationOptions<
		CategoriesControllerCreateStatus201,
		ResponseErrorConfig<
			| CategoriesControllerCreateStatus401
			| CategoriesControllerCreateStatus403
			| CategoriesControllerCreateStatus409
		>,
		CategoriesControllerCreateOptions,
		TContext
	>;

	return useMutation<
		CategoriesControllerCreateStatus201,
		ResponseErrorConfig<
			| CategoriesControllerCreateStatus401
			| CategoriesControllerCreateStatus403
			| CategoriesControllerCreateStatus409
		>,
		CategoriesControllerCreateOptions,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		CategoriesControllerCreateStatus201,
		ResponseErrorConfig<
			| CategoriesControllerCreateStatus401
			| CategoriesControllerCreateStatus403
			| CategoriesControllerCreateStatus409
		>,
		CategoriesControllerCreateOptions,
		TContext
	>;
}
