/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	CategoriesControllerGetByIdOptions,
	CategoriesControllerGetByIdStatus200,
	CategoriesControllerGetByIdStatus401,
	CategoriesControllerGetByIdStatus404,
} from "../../schemas/categories/CategoriesControllerGetById";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { categoriesControllerGetById } from "../categoriesControllerGetById";

export const categoriesControllerGetByIdQueryKey = ({
	path,
}: Omit<CategoriesControllerGetByIdOptions, "headers">) =>
	[{ url: "/v1/categories/:id", params: path }] as const;

type CategoriesControllerGetByIdQueryKey = ReturnType<
	typeof categoriesControllerGetByIdQueryKey
>;

export function categoriesControllerGetByIdQueryOptions(
	{ path }: CategoriesControllerGetByIdOptions,
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const queryKey = categoriesControllerGetByIdQueryKey({ path });
	return queryOptions<
		CategoriesControllerGetByIdStatus200,
		ResponseErrorConfig<
			| CategoriesControllerGetByIdStatus401
			| CategoriesControllerGetByIdStatus404
		>,
		CategoriesControllerGetByIdStatus200,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return await categoriesControllerGetById({
				...config,
				path,
				signal: config.signal ?? signal,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/categories/:id}
 */
export function useCategoriesControllerGetById<
	TData = CategoriesControllerGetByIdStatus200,
	TQueryData = CategoriesControllerGetByIdStatus200,
	TQueryKey extends QueryKey = CategoriesControllerGetByIdQueryKey,
>(
	{
		path,
	}: {
		path:
			| CategoriesControllerGetByIdOptions["path"]
			| (() => CategoriesControllerGetByIdOptions["path"]);
	},
	options: {
		query?: Partial<
			QueryObserverOptions<
				CategoriesControllerGetByIdStatus200,
				ResponseErrorConfig<
					| CategoriesControllerGetByIdStatus401
					| CategoriesControllerGetByIdStatus404
				>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const resolvedParams = { path: typeof path === "function" ? path() : path };
	const queryKey =
		resolvedOptions?.queryKey ??
		categoriesControllerGetByIdQueryKey(resolvedParams);

	const queryResult = useQuery(
		{
			...categoriesControllerGetByIdQueryOptions(resolvedParams, config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<
		TData,
		ResponseErrorConfig<
			| CategoriesControllerGetByIdStatus401
			| CategoriesControllerGetByIdStatus404
		>
	> & { queryKey: TQueryKey };

	queryResult.queryKey = queryKey as TQueryKey;

	return queryResult;
}
