/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	CategoriesControllerListStatus200,
	CategoriesControllerListStatus401,
} from "../../schemas/categories/CategoriesControllerList";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { categoriesControllerList } from "../categoriesControllerList";

export const categoriesControllerListQueryKey = () =>
	[{ url: "/v1/categories" }] as const;

type CategoriesControllerListQueryKey = ReturnType<
	typeof categoriesControllerListQueryKey
>;

export function categoriesControllerListQueryOptions(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const queryKey = categoriesControllerListQueryKey();
	return queryOptions<
		CategoriesControllerListStatus200,
		ResponseErrorConfig<CategoriesControllerListStatus401>,
		CategoriesControllerListStatus200,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return await categoriesControllerList({
				...config,
				signal: config.signal ?? signal,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/categories}
 */
export function useCategoriesControllerList<
	TData = CategoriesControllerListStatus200,
	TQueryData = CategoriesControllerListStatus200,
	TQueryKey extends QueryKey = CategoriesControllerListQueryKey,
>(
	options: {
		query?: Partial<
			QueryObserverOptions<
				CategoriesControllerListStatus200,
				ResponseErrorConfig<CategoriesControllerListStatus401>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey =
		resolvedOptions?.queryKey ?? categoriesControllerListQueryKey();

	const queryResult = useQuery(
		{
			...categoriesControllerListQueryOptions(config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<
		TData,
		ResponseErrorConfig<CategoriesControllerListStatus401>
	> & { queryKey: TQueryKey };

	queryResult.queryKey = queryKey as TQueryKey;

	return queryResult;
}
