/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	CategoriesControllerUpdateOptions,
	CategoriesControllerUpdateStatus200,
	CategoriesControllerUpdateStatus401,
	CategoriesControllerUpdateStatus403,
	CategoriesControllerUpdateStatus404,
	CategoriesControllerUpdateStatus409,
} from "../../schemas/categories/CategoriesControllerUpdate";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { categoriesControllerUpdate } from "../categoriesControllerUpdate";

export const categoriesControllerUpdateMutationKey = () =>
	[{ url: "/v1/categories/:id" }] as const;

export function categoriesControllerUpdateMutationOptions<TContext = unknown>(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const mutationKey = categoriesControllerUpdateMutationKey();
	return mutationOptions<
		CategoriesControllerUpdateStatus200,
		ResponseErrorConfig<
			| CategoriesControllerUpdateStatus401
			| CategoriesControllerUpdateStatus403
			| CategoriesControllerUpdateStatus404
			| CategoriesControllerUpdateStatus409
		>,
		CategoriesControllerUpdateOptions,
		TContext
	>({
		mutationKey,
		mutationFn: async ({ path, body }) => {
			return await categoriesControllerUpdate({
				...config,
				path,
				body,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/categories/:id}
 */
export function useCategoriesControllerUpdate<TContext>(
	options: {
		mutation?: UseMutationOptions<
			CategoriesControllerUpdateStatus200,
			ResponseErrorConfig<
				| CategoriesControllerUpdateStatus401
				| CategoriesControllerUpdateStatus403
				| CategoriesControllerUpdateStatus404
				| CategoriesControllerUpdateStatus409
			>,
			CategoriesControllerUpdateOptions,
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? categoriesControllerUpdateMutationKey();

	const baseOptions = categoriesControllerUpdateMutationOptions(
		config,
	) as UseMutationOptions<
		CategoriesControllerUpdateStatus200,
		ResponseErrorConfig<
			| CategoriesControllerUpdateStatus401
			| CategoriesControllerUpdateStatus403
			| CategoriesControllerUpdateStatus404
			| CategoriesControllerUpdateStatus409
		>,
		CategoriesControllerUpdateOptions,
		TContext
	>;

	return useMutation<
		CategoriesControllerUpdateStatus200,
		ResponseErrorConfig<
			| CategoriesControllerUpdateStatus401
			| CategoriesControllerUpdateStatus403
			| CategoriesControllerUpdateStatus404
			| CategoriesControllerUpdateStatus409
		>,
		CategoriesControllerUpdateOptions,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		CategoriesControllerUpdateStatus200,
		ResponseErrorConfig<
			| CategoriesControllerUpdateStatus401
			| CategoriesControllerUpdateStatus403
			| CategoriesControllerUpdateStatus404
			| CategoriesControllerUpdateStatus409
		>,
		CategoriesControllerUpdateOptions,
		TContext
	>;
}
