/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	CategoriesControllerRemoveOptions,
	CategoriesControllerRemoveStatus200,
	CategoriesControllerRemoveStatus401,
	CategoriesControllerRemoveStatus403,
	CategoriesControllerRemoveStatus404,
	CategoriesControllerRemoveStatus409,
} from "../../schemas/categories/CategoriesControllerRemove";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { categoriesControllerRemove } from "../categoriesControllerRemove";

export const categoriesControllerRemoveMutationKey = () =>
	[{ url: "/v1/categories/:id" }] as const;

export function categoriesControllerRemoveMutationOptions<TContext = unknown>(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const mutationKey = categoriesControllerRemoveMutationKey();
	return mutationOptions<
		CategoriesControllerRemoveStatus200,
		ResponseErrorConfig<
			| CategoriesControllerRemoveStatus401
			| CategoriesControllerRemoveStatus403
			| CategoriesControllerRemoveStatus404
			| CategoriesControllerRemoveStatus409
		>,
		CategoriesControllerRemoveOptions,
		TContext
	>({
		mutationKey,
		mutationFn: async ({ path }) => {
			return await categoriesControllerRemove({
				...config,
				path,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/categories/:id}
 */
export function useCategoriesControllerRemove<TContext>(
	options: {
		mutation?: UseMutationOptions<
			CategoriesControllerRemoveStatus200,
			ResponseErrorConfig<
				| CategoriesControllerRemoveStatus401
				| CategoriesControllerRemoveStatus403
				| CategoriesControllerRemoveStatus404
				| CategoriesControllerRemoveStatus409
			>,
			CategoriesControllerRemoveOptions,
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? categoriesControllerRemoveMutationKey();

	const baseOptions = categoriesControllerRemoveMutationOptions(
		config,
	) as UseMutationOptions<
		CategoriesControllerRemoveStatus200,
		ResponseErrorConfig<
			| CategoriesControllerRemoveStatus401
			| CategoriesControllerRemoveStatus403
			| CategoriesControllerRemoveStatus404
			| CategoriesControllerRemoveStatus409
		>,
		CategoriesControllerRemoveOptions,
		TContext
	>;

	return useMutation<
		CategoriesControllerRemoveStatus200,
		ResponseErrorConfig<
			| CategoriesControllerRemoveStatus401
			| CategoriesControllerRemoveStatus403
			| CategoriesControllerRemoveStatus404
			| CategoriesControllerRemoveStatus409
		>,
		CategoriesControllerRemoveOptions,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		CategoriesControllerRemoveStatus200,
		ResponseErrorConfig<
			| CategoriesControllerRemoveStatus401
			| CategoriesControllerRemoveStatus403
			| CategoriesControllerRemoveStatus404
			| CategoriesControllerRemoveStatus409
		>,
		CategoriesControllerRemoveOptions,
		TContext
	>;
}
