/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type { AppControllerGetHealthStatus200 } from "../../schemas/health/AppControllerGetHealth";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { appControllerGetHealth } from "../appControllerGetHealth";

export const appControllerGetHealthQueryKey = () => [{ url: "/v1" }] as const;

type AppControllerGetHealthQueryKey = ReturnType<
	typeof appControllerGetHealthQueryKey
>;

export function appControllerGetHealthQueryOptions(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const queryKey = appControllerGetHealthQueryKey();
	return queryOptions<
		AppControllerGetHealthStatus200,
		ResponseErrorConfig<Error>,
		AppControllerGetHealthStatus200,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return await appControllerGetHealth({
				...config,
				signal: config.signal ?? signal,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1}
 */
export function useAppControllerGetHealth<
	TData = AppControllerGetHealthStatus200,
	TQueryData = AppControllerGetHealthStatus200,
	TQueryKey extends QueryKey = AppControllerGetHealthQueryKey,
>(
	options: {
		query?: Partial<
			QueryObserverOptions<
				AppControllerGetHealthStatus200,
				ResponseErrorConfig<Error>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey =
		resolvedOptions?.queryKey ?? appControllerGetHealthQueryKey();

	const queryResult = useQuery(
		{
			...appControllerGetHealthQueryOptions(config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
		queryKey: TQueryKey;
	};

	queryResult.queryKey = queryKey as TQueryKey;

	return queryResult;
}
