/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type {
	AuthControllerRegisterMutationRequest,
	AuthControllerRegisterMutationResponse,
	AuthControllerRegister409,
} from "../../schemas/auth/auth-controller-register.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { authControllerRegister } from "../auth-controller-register.ts";

export const authControllerRegisterMutationKey = () =>
	[{ url: "/v1/auth/register" }] as const;

export type AuthControllerRegisterMutationKey = ReturnType<
	typeof authControllerRegisterMutationKey
>;

export function useAuthControllerRegisterMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<AuthControllerRegisterMutationRequest>> & {
		client?: Client;
	} = {},
) {
	const mutationKey = authControllerRegisterMutationKey();
	return mutationOptions<
		AuthControllerRegisterMutationResponse,
		ResponseErrorConfig<AuthControllerRegister409>,
		{ data: AuthControllerRegisterMutationRequest },
		TContext
	>({
		mutationKey,
		mutationFn: async ({ data }) => {
			return authControllerRegister(data, config);
		},
	});
}

/**
 * {@link /v1/auth/register}
 */
export function useAuthControllerRegister<TContext>(
	options: {
		mutation?: UseMutationOptions<
			AuthControllerRegisterMutationResponse,
			ResponseErrorConfig<AuthControllerRegister409>,
			{ data: AuthControllerRegisterMutationRequest },
			TContext
		> & { client?: QueryClient };
		client?: Partial<RequestConfig<AuthControllerRegisterMutationRequest>> & {
			client?: Client;
		};
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? authControllerRegisterMutationKey();

	const baseOptions = useAuthControllerRegisterMutationOptions(
		config,
	) as UseMutationOptions<
		AuthControllerRegisterMutationResponse,
		ResponseErrorConfig<AuthControllerRegister409>,
		{ data: AuthControllerRegisterMutationRequest },
		TContext
	>;

	return useMutation<
		AuthControllerRegisterMutationResponse,
		ResponseErrorConfig<AuthControllerRegister409>,
		{ data: AuthControllerRegisterMutationRequest },
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		AuthControllerRegisterMutationResponse,
		ResponseErrorConfig<AuthControllerRegister409>,
		{ data: AuthControllerRegisterMutationRequest },
		TContext
	>;
}
