/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	AuthControllerRegisterOptions,
	AuthControllerRegisterStatus201,
	AuthControllerRegisterStatus409,
} from "../../schemas/auth/AuthControllerRegister";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { authControllerRegister } from "../authControllerRegister";

export const authControllerRegisterMutationKey = () =>
	[{ url: "/v1/auth/register" }] as const;

export function authControllerRegisterMutationOptions<TContext = unknown>(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const mutationKey = authControllerRegisterMutationKey();
	return mutationOptions<
		AuthControllerRegisterStatus201,
		ResponseErrorConfig<AuthControllerRegisterStatus409>,
		AuthControllerRegisterOptions,
		TContext
	>({
		mutationKey,
		mutationFn: async ({ body }) => {
			return await authControllerRegister({
				...config,
				body,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/auth/register}
 */
export function useAuthControllerRegister<TContext>(
	options: {
		mutation?: UseMutationOptions<
			AuthControllerRegisterStatus201,
			ResponseErrorConfig<AuthControllerRegisterStatus409>,
			AuthControllerRegisterOptions,
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? authControllerRegisterMutationKey();

	const baseOptions = authControllerRegisterMutationOptions(
		config,
	) as UseMutationOptions<
		AuthControllerRegisterStatus201,
		ResponseErrorConfig<AuthControllerRegisterStatus409>,
		AuthControllerRegisterOptions,
		TContext
	>;

	return useMutation<
		AuthControllerRegisterStatus201,
		ResponseErrorConfig<AuthControllerRegisterStatus409>,
		AuthControllerRegisterOptions,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		AuthControllerRegisterStatus201,
		ResponseErrorConfig<AuthControllerRegisterStatus409>,
		AuthControllerRegisterOptions,
		TContext
	>;
}
