/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	AuthControllerLoginOptions,
	AuthControllerLoginStatus200,
	AuthControllerLoginStatus401,
} from "../../schemas/auth/AuthControllerLogin";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { authControllerLogin } from "../authControllerLogin";

export const authControllerLoginMutationKey = () =>
	[{ url: "/v1/auth/login" }] as const;

export function authControllerLoginMutationOptions<TContext = unknown>(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const mutationKey = authControllerLoginMutationKey();
	return mutationOptions<
		AuthControllerLoginStatus200,
		ResponseErrorConfig<AuthControllerLoginStatus401>,
		AuthControllerLoginOptions,
		TContext
	>({
		mutationKey,
		mutationFn: async ({ body, headers }) => {
			return await authControllerLogin({
				...config,
				body,
				headers,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/auth/login}
 */
export function useAuthControllerLogin<TContext>(
	options: {
		mutation?: UseMutationOptions<
			AuthControllerLoginStatus200,
			ResponseErrorConfig<AuthControllerLoginStatus401>,
			AuthControllerLoginOptions,
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? authControllerLoginMutationKey();

	const baseOptions = authControllerLoginMutationOptions(
		config,
	) as UseMutationOptions<
		AuthControllerLoginStatus200,
		ResponseErrorConfig<AuthControllerLoginStatus401>,
		AuthControllerLoginOptions,
		TContext
	>;

	return useMutation<
		AuthControllerLoginStatus200,
		ResponseErrorConfig<AuthControllerLoginStatus401>,
		AuthControllerLoginOptions,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		AuthControllerLoginStatus200,
		ResponseErrorConfig<AuthControllerLoginStatus401>,
		AuthControllerLoginOptions,
		TContext
	>;
}
