/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	AuthControllerForgotPasswordOptions,
	AuthControllerForgotPasswordStatus200,
} from "../../schemas/auth/AuthControllerForgotPassword";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { authControllerForgotPassword } from "../authControllerForgotPassword";

export const authControllerForgotPasswordMutationKey = () =>
	[{ url: "/v1/auth/forgot-password" }] as const;

export function authControllerForgotPasswordMutationOptions<TContext = unknown>(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const mutationKey = authControllerForgotPasswordMutationKey();
	return mutationOptions<
		AuthControllerForgotPasswordStatus200,
		ResponseErrorConfig<Error>,
		AuthControllerForgotPasswordOptions,
		TContext
	>({
		mutationKey,
		mutationFn: async ({ body }) => {
			return await authControllerForgotPassword({
				...config,
				body,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/auth/forgot-password}
 */
export function useAuthControllerForgotPassword<TContext>(
	options: {
		mutation?: UseMutationOptions<
			AuthControllerForgotPasswordStatus200,
			ResponseErrorConfig<Error>,
			AuthControllerForgotPasswordOptions,
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? authControllerForgotPasswordMutationKey();

	const baseOptions = authControllerForgotPasswordMutationOptions(
		config,
	) as UseMutationOptions<
		AuthControllerForgotPasswordStatus200,
		ResponseErrorConfig<Error>,
		AuthControllerForgotPasswordOptions,
		TContext
	>;

	return useMutation<
		AuthControllerForgotPasswordStatus200,
		ResponseErrorConfig<Error>,
		AuthControllerForgotPasswordOptions,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		AuthControllerForgotPasswordStatus200,
		ResponseErrorConfig<Error>,
		AuthControllerForgotPasswordOptions,
		TContext
	>;
}
