/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type { AuthControllerLogoutStatus200 } from "../../schemas/auth/AuthControllerLogout";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { authControllerLogout } from "../authControllerLogout";

export const authControllerLogoutMutationKey = () =>
	[{ url: "/v1/auth/logout" }] as const;

export function authControllerLogoutMutationOptions<TContext = unknown>(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const mutationKey = authControllerLogoutMutationKey();
	return mutationOptions<
		AuthControllerLogoutStatus200,
		ResponseErrorConfig<Error>,
		undefined,
		TContext
	>({
		mutationKey,
		mutationFn: async (_) => {
			return await authControllerLogout({ ...config, throwOnError: true });
		},
	});
}

/**
 * {@link /v1/auth/logout}
 */
export function useAuthControllerLogout<TContext>(
	options: {
		mutation?: UseMutationOptions<
			AuthControllerLogoutStatus200,
			ResponseErrorConfig<Error>,
			undefined,
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? authControllerLogoutMutationKey();

	const baseOptions = authControllerLogoutMutationOptions(
		config,
	) as UseMutationOptions<
		AuthControllerLogoutStatus200,
		ResponseErrorConfig<Error>,
		undefined,
		TContext
	>;

	return useMutation<
		AuthControllerLogoutStatus200,
		ResponseErrorConfig<Error>,
		undefined,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		AuthControllerLogoutStatus200,
		ResponseErrorConfig<Error>,
		undefined,
		TContext
	>;
}
