/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	AuthControllerMeStatus200,
	AuthControllerMeStatus401,
} from "../../schemas/auth/AuthControllerMe";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { authControllerMe } from "../authControllerMe";

export const authControllerMeQueryKey = () => [{ url: "/v1/auth/me" }] as const;

type AuthControllerMeQueryKey = ReturnType<typeof authControllerMeQueryKey>;

export function authControllerMeQueryOptions(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const queryKey = authControllerMeQueryKey();
	return queryOptions<
		AuthControllerMeStatus200,
		ResponseErrorConfig<AuthControllerMeStatus401>,
		AuthControllerMeStatus200,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return await authControllerMe({
				...config,
				signal: config.signal ?? signal,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/auth/me}
 */
export function useAuthControllerMe<
	TData = AuthControllerMeStatus200,
	TQueryData = AuthControllerMeStatus200,
	TQueryKey extends QueryKey = AuthControllerMeQueryKey,
>(
	options: {
		query?: Partial<
			QueryObserverOptions<
				AuthControllerMeStatus200,
				ResponseErrorConfig<AuthControllerMeStatus401>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey = resolvedOptions?.queryKey ?? authControllerMeQueryKey();

	const queryResult = useQuery(
		{
			...authControllerMeQueryOptions(config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<AuthControllerMeStatus401>> & {
		queryKey: TQueryKey;
	};

	queryResult.queryKey = queryKey as TQueryKey;

	return queryResult;
}
