/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	AuthControllerResetPasswordOptions,
	AuthControllerResetPasswordStatus200,
	AuthControllerResetPasswordStatus401,
} from "../../schemas/auth/AuthControllerResetPassword";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { authControllerResetPassword } from "../authControllerResetPassword";

export const authControllerResetPasswordMutationKey = () =>
	[{ url: "/v1/auth/reset-password" }] as const;

export function authControllerResetPasswordMutationOptions<TContext = unknown>(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const mutationKey = authControllerResetPasswordMutationKey();
	return mutationOptions<
		AuthControllerResetPasswordStatus200,
		ResponseErrorConfig<AuthControllerResetPasswordStatus401>,
		AuthControllerResetPasswordOptions,
		TContext
	>({
		mutationKey,
		mutationFn: async ({ body }) => {
			return await authControllerResetPassword({
				...config,
				body,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/auth/reset-password}
 */
export function useAuthControllerResetPassword<TContext>(
	options: {
		mutation?: UseMutationOptions<
			AuthControllerResetPasswordStatus200,
			ResponseErrorConfig<AuthControllerResetPasswordStatus401>,
			AuthControllerResetPasswordOptions,
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? authControllerResetPasswordMutationKey();

	const baseOptions = authControllerResetPasswordMutationOptions(
		config,
	) as UseMutationOptions<
		AuthControllerResetPasswordStatus200,
		ResponseErrorConfig<AuthControllerResetPasswordStatus401>,
		AuthControllerResetPasswordOptions,
		TContext
	>;

	return useMutation<
		AuthControllerResetPasswordStatus200,
		ResponseErrorConfig<AuthControllerResetPasswordStatus401>,
		AuthControllerResetPasswordOptions,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		AuthControllerResetPasswordStatus200,
		ResponseErrorConfig<AuthControllerResetPasswordStatus401>,
		AuthControllerResetPasswordOptions,
		TContext
	>;
}
