/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResetPasswordDto } from "../ResetPasswordDto";
import type { SuccessResponseDto } from "../SuccessResponseDto";

export type AuthControllerResetPasswordStatus200 = SuccessResponseDto;

export type AuthControllerResetPasswordStatus401 = unknown;

export type AuthControllerResetPasswordBody = ResetPasswordDto;

export type AuthControllerResetPasswordOptions = {
	body: AuthControllerResetPasswordBody;
	path?: never;
	query?: never;
	headers?: never;
};

export type AuthControllerResetPasswordResponses = {
	"200": AuthControllerResetPasswordStatus200;
	"401": AuthControllerResetPasswordStatus401;
};

/**
 * @description Union of all possible responses
 */
export type AuthControllerResetPasswordResponse =
	AuthControllerResetPasswordStatus200;
