/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { SuccessResponseDto } from "../success-response-dto.ts";

export type AuthControllerLogout200 = SuccessResponseDto;

export type AuthControllerLogoutMutationResponse = AuthControllerLogout200;

export type AuthControllerLogoutMutation = {
	Response: AuthControllerLogout200;
	Errors: any;
};
