/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { LoginResponseDto } from "../login-response-dto.ts";
import type { RegisterDto } from "../register-dto.ts";

/**
 * @description Conta criada e sessão iniciada
 */
export type AuthControllerRegister201 = LoginResponseDto;

/**
 * @description E-mail já está em uso
 */
export type AuthControllerRegister409 = any;

export type AuthControllerRegisterMutationRequest = RegisterDto;

export type AuthControllerRegisterMutationResponse = AuthControllerRegister201;

export type AuthControllerRegisterMutation = {
	Response: AuthControllerRegister201;
	Request: AuthControllerRegisterMutationRequest;
	Errors: AuthControllerRegister409;
};
