/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { LoginDto } from "../LoginDto";
import type { LoginResponseDto } from "../LoginResponseDto";

export type AuthControllerLoginStatus200 = LoginResponseDto;

export type AuthControllerLoginStatus401 = unknown;

export type AuthControllerLoginBody = LoginDto;

export type AuthControllerLoginOptions = {
	body: AuthControllerLoginBody;
	path?: never;
	query?: never;
	headers?: never;
};

export type AuthControllerLoginResponses = {
	"200": AuthControllerLoginStatus200;
	"401": AuthControllerLoginStatus401;
};

/**
 * @description Union of all possible responses
 */
export type AuthControllerLoginResponse = AuthControllerLoginStatus200;
