/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { LoginDto } from "../login-dto.ts";
import type { LoginResponseDto } from "../login-response-dto.ts";

/**
 * @description Login realizado com sucesso
 */
export type AuthControllerLogin200 = LoginResponseDto;

/**
 * @description Credenciais inválidas
 */
export type AuthControllerLogin401 = any;

export type AuthControllerLoginMutationRequest = LoginDto;

export type AuthControllerLoginMutationResponse = AuthControllerLogin200;

export type AuthControllerLoginMutation = {
	Response: AuthControllerLogin200;
	Request: AuthControllerLoginMutationRequest;
	Errors: AuthControllerLogin401;
};
