/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MeResponseDto } from "../me-response-dto.ts";

/**
 * @description Dados do usuário autenticado
 */
export type AuthControllerMe200 = MeResponseDto;

/**
 * @description Não autenticado
 */
export type AuthControllerMe401 = any;

export type AuthControllerMeQueryResponse = AuthControllerMe200;

export type AuthControllerMeQuery = {
	Response: AuthControllerMe200;
	Errors: AuthControllerMe401;
};
