/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { LoginResponseDto } from "../LoginResponseDto";
import type { RegisterDto } from "../RegisterDto";

export type AuthControllerRegisterHeaders = {
	/**
	 * @description Enviar \"mobile\" pra receber accessToken também no body (sem isso, só o cookie httpOnly é setado)
	 * @type string | undefined
	 */
	"x-client-platform"?: string;
};

export type AuthControllerRegisterStatus201 = LoginResponseDto;

export type AuthControllerRegisterStatus409 = unknown;

export type AuthControllerRegisterBody = RegisterDto;

export type AuthControllerRegisterOptions = {
	body: AuthControllerRegisterBody;
	path?: never;
	query?: never;
	headers?: AuthControllerRegisterHeaders;
};

export type AuthControllerRegisterResponses = {
	"201": AuthControllerRegisterStatus201;
	"409": AuthControllerRegisterStatus409;
};

/**
 * @description Union of all possible responses
 */
export type AuthControllerRegisterResponse = AuthControllerRegisterStatus201;
