/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { LoginDto } from "../LoginDto";
import type { LoginResponseDto } from "../LoginResponseDto";

export type AuthControllerLoginHeaders = {
	/**
	 * @description Enviar \"mobile\" pra receber accessToken também no body (sem isso, só o cookie httpOnly é setado)
	 * @type string | undefined
	 */
	"x-client-platform"?: string;
};

export type AuthControllerLoginStatus200 = LoginResponseDto;

export type AuthControllerLoginStatus401 = unknown;

export type AuthControllerLoginBody = LoginDto;

export type AuthControllerLoginOptions = {
	body: AuthControllerLoginBody;
	path?: never;
	query?: never;
	headers?: AuthControllerLoginHeaders;
};

export type AuthControllerLoginResponses = {
	"200": AuthControllerLoginStatus200;
	"401": AuthControllerLoginStatus401;
};

/**
 * @description Union of all possible responses
 */
export type AuthControllerLoginResponse = AuthControllerLoginStatus200;
