/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { LoginResponseDto } from "../LoginResponseDto";
import type { RegisterDto } from "../RegisterDto";

export type AuthControllerRegisterStatus201 = LoginResponseDto;

export type AuthControllerRegisterStatus409 = unknown;

export type AuthControllerRegisterBody = RegisterDto;

export type AuthControllerRegisterOptions = {
	body: AuthControllerRegisterBody;
	path?: never;
	query?: never;
	headers?: never;
};

export type AuthControllerRegisterResponses = {
	"201": AuthControllerRegisterStatus201;
	"409": AuthControllerRegisterStatus409;
};

/**
 * @description Union of all possible responses
 */
export type AuthControllerRegisterResponse = AuthControllerRegisterStatus201;
