/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { SuccessResponseDto } from "../SuccessResponseDto";

export type AuthControllerLogoutStatus200 = SuccessResponseDto;

export type AuthControllerLogoutOptions = {
	body?: never;
	path?: never;
	query?: never;
	headers?: never;
};

export type AuthControllerLogoutResponses = {
	"200": AuthControllerLogoutStatus200;
};

/**
 * @description Union of all possible responses
 */
export type AuthControllerLogoutResponse = AuthControllerLogoutStatus200;
