/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ForgotPasswordDto } from "../ForgotPasswordDto";
import type { ForgotPasswordResponseDto } from "../ForgotPasswordResponseDto";

export type AuthControllerForgotPasswordStatus200 = ForgotPasswordResponseDto;

export type AuthControllerForgotPasswordBody = ForgotPasswordDto;

export type AuthControllerForgotPasswordOptions = {
	body: AuthControllerForgotPasswordBody;
	path?: never;
	query?: never;
	headers?: never;
};

export type AuthControllerForgotPasswordResponses = {
	"200": AuthControllerForgotPasswordStatus200;
};

/**
 * @description Union of all possible responses
 */
export type AuthControllerForgotPasswordResponse =
	AuthControllerForgotPasswordStatus200;
