/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ForgotPasswordDto } from "../forgot-password-dto.ts";
import type { ForgotPasswordResponseDto } from "../forgot-password-response-dto.ts";

/**
 * @description Solicitação de recuperação recebida
 */
export type AuthControllerForgotPassword200 = ForgotPasswordResponseDto;

export type AuthControllerForgotPasswordMutationRequest = ForgotPasswordDto;

export type AuthControllerForgotPasswordMutationResponse =
	AuthControllerForgotPassword200;

export type AuthControllerForgotPasswordMutation = {
	Response: AuthControllerForgotPassword200;
	Request: AuthControllerForgotPasswordMutationRequest;
	Errors: any;
};
