/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResetPasswordDto } from "../reset-password-dto.ts";
import type { SuccessResponseDto } from "../success-response-dto.ts";

export type AuthControllerResetPassword200 = SuccessResponseDto;

/**
 * @description Token de recuperação inválido ou expirado
 */
export type AuthControllerResetPassword401 = any;

export type AuthControllerResetPasswordMutationRequest = ResetPasswordDto;

export type AuthControllerResetPasswordMutationResponse =
	AuthControllerResetPassword200;

export type AuthControllerResetPasswordMutation = {
	Response: AuthControllerResetPassword200;
	Request: AuthControllerResetPasswordMutationRequest;
	Errors: AuthControllerResetPassword401;
};
