/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MeResponseDto } from "../MeResponseDto";

export type AuthControllerMeStatus200 = MeResponseDto;

export type AuthControllerMeStatus401 = unknown;

export type AuthControllerMeOptions = {
	body?: never;
	path?: never;
	query?: never;
	headers?: never;
};

export type AuthControllerMeResponses = {
	"200": AuthControllerMeStatus200;
	"401": AuthControllerMeStatus401;
};

/**
 * @description Union of all possible responses
 */
export type AuthControllerMeResponse = AuthControllerMeStatus200;
