/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DashboardResponseDto } from "../dashboard-response-dto.ts";

export type DashboardControllerGetSummaryQueryParams = {
	/**
	 * @description Formato YYYY-MM
	 * @type string | undefined
	 */
	month?: string;
};

export type DashboardControllerGetSummary200 = DashboardResponseDto;

/**
 * @description Formato de mês inválido (YYYY-MM)
 */
export type DashboardControllerGetSummary400 = any;

/**
 * @description Não autenticado
 */
export type DashboardControllerGetSummary401 = any;

export type DashboardControllerGetSummaryQueryResponse =
	DashboardControllerGetSummary200;

export type DashboardControllerGetSummaryQuery = {
	Response: DashboardControllerGetSummary200;
	QueryParams: DashboardControllerGetSummaryQueryParams;
	Errors: DashboardControllerGetSummary400 | DashboardControllerGetSummary401;
};
