/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DashboardResponseDto } from "../DashboardResponseDto";

export type DashboardControllerGetSummaryQuery = {
	/**
	 * @description Formato YYYY-MM
	 * @example 2026-03
	 * @type string | undefined
	 */
	month?: string;
};

export type DashboardControllerGetSummaryStatus200 = DashboardResponseDto;

export type DashboardControllerGetSummaryStatus400 = unknown;

export type DashboardControllerGetSummaryStatus401 = unknown;

export type DashboardControllerGetSummaryOptions = {
	body?: never;
	path?: never;
	query?: DashboardControllerGetSummaryQuery;
	headers?: never;
};

export type DashboardControllerGetSummaryResponses = {
	"200": DashboardControllerGetSummaryStatus200;
	"400": DashboardControllerGetSummaryStatus400;
	"401": DashboardControllerGetSummaryStatus401;
};

/**
 * @description Union of all possible responses
 */
export type DashboardControllerGetSummaryResponse =
	DashboardControllerGetSummaryStatus200;
