/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	AttachmentsControllerRemoveMutationResponse,
	AttachmentsControllerRemovePathParams,
	AttachmentsControllerRemove404,
} from "../schemas/attachments/attachments-controller-remove.ts";

function getAttachmentsControllerRemoveUrl(
	id: AttachmentsControllerRemovePathParams["id"],
) {
	const res = { method: "DELETE", url: `/v1/attachments/${id}` as const };
	return res;
}

/**
 * {@link /v1/attachments/:id}
 */
export async function attachmentsControllerRemove(
	id: AttachmentsControllerRemovePathParams["id"],
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		AttachmentsControllerRemoveMutationResponse,
		ResponseErrorConfig<AttachmentsControllerRemove404>,
		unknown
	>({
		method: "DELETE",
		url: getAttachmentsControllerRemoveUrl(id).url.toString(),
		...requestConfig,
	});
	return res.data;
}
