/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	AttachmentsControllerRemoveOptions,
	AttachmentsControllerRemoveResponses,
} from "../schemas/attachments/AttachmentsControllerRemove";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/attachments/:id}
 */
export function attachmentsControllerRemove<
	ThrowOnError extends boolean = true,
>(
	options: Options<AttachmentsControllerRemoveOptions, ThrowOnError>,
): Promise<
	UnwrappedResult<AttachmentsControllerRemoveResponses, ThrowOnError>
> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "DELETE",
			url: "/v1/attachments/{id}",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<AttachmentsControllerRemoveResponses, ThrowOnError>
	>;
}
