/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	AttachmentsControllerGetDownloadUrlQueryResponse,
	AttachmentsControllerGetDownloadUrlPathParams,
	AttachmentsControllerGetDownloadUrl404,
} from "../schemas/attachments/attachments-controller-get-download-url.ts";

function getAttachmentsControllerGetDownloadUrlUrl(
	id: AttachmentsControllerGetDownloadUrlPathParams["id"],
) {
	const res = { method: "GET", url: `/v1/attachments/${id}/download` as const };
	return res;
}

/**
 * {@link /v1/attachments/:id/download}
 */
export async function attachmentsControllerGetDownloadUrl(
	id: AttachmentsControllerGetDownloadUrlPathParams["id"],
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		AttachmentsControllerGetDownloadUrlQueryResponse,
		ResponseErrorConfig<AttachmentsControllerGetDownloadUrl404>,
		unknown
	>({
		method: "GET",
		url: getAttachmentsControllerGetDownloadUrlUrl(id).url.toString(),
		...requestConfig,
	});
	return res.data;
}
