/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	AttachmentsControllerGetDownloadUrlOptions,
	AttachmentsControllerGetDownloadUrlResponses,
} from "../schemas/attachments/AttachmentsControllerGetDownloadUrl";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/attachments/:id/download}
 */
export function attachmentsControllerGetDownloadUrl<
	ThrowOnError extends boolean = true,
>(
	options: Options<AttachmentsControllerGetDownloadUrlOptions, ThrowOnError>,
): Promise<
	UnwrappedResult<AttachmentsControllerGetDownloadUrlResponses, ThrowOnError>
> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "GET",
			url: "/v1/attachments/{id}/download",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<AttachmentsControllerGetDownloadUrlResponses, ThrowOnError>
	>;
}
