/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	TransactionAttachmentsControllerUploadMutationResponse,
	TransactionAttachmentsControllerUploadPathParams,
	TransactionAttachmentsControllerUpload400,
	TransactionAttachmentsControllerUpload404,
} from "../schemas/attachments/transaction-attachments-controller-upload.ts";

function getTransactionAttachmentsControllerUploadUrl(
	transactionId: TransactionAttachmentsControllerUploadPathParams["transactionId"],
) {
	const res = {
		method: "POST",
		url: `/v1/transactions/${transactionId}/attachments` as const,
	};
	return res;
}

/**
 * {@link /v1/transactions/:transactionId/attachments}
 */
export async function transactionAttachmentsControllerUpload(
	transactionId: TransactionAttachmentsControllerUploadPathParams["transactionId"],
	data: FormData,
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		TransactionAttachmentsControllerUploadMutationResponse,
		ResponseErrorConfig<
			| TransactionAttachmentsControllerUpload400
			| TransactionAttachmentsControllerUpload404
		>,
		FormData
	>({
		method: "POST",
		url: getTransactionAttachmentsControllerUploadUrl(transactionId).url.toString(),
		...requestConfig,
		data,
	});
	return res.data;
}
