/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	TransactionAttachmentsControllerListOptions,
	TransactionAttachmentsControllerListResponses,
} from "../schemas/attachments/TransactionAttachmentsControllerList";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/transactions/:transactionId/attachments}
 */
export function transactionAttachmentsControllerList<
	ThrowOnError extends boolean = true,
>(
	options: Options<TransactionAttachmentsControllerListOptions, ThrowOnError>,
): Promise<
	UnwrappedResult<TransactionAttachmentsControllerListResponses, ThrowOnError>
> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "GET",
			url: "/v1/transactions/{transactionId}/attachments",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<TransactionAttachmentsControllerListResponses, ThrowOnError>
	>;
}
