/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	TransactionAttachmentsControllerListQueryResponse,
	TransactionAttachmentsControllerListPathParams,
	TransactionAttachmentsControllerList404,
} from "../schemas/attachments/transaction-attachments-controller-list.ts";

function getTransactionAttachmentsControllerListUrl(
	transactionId: TransactionAttachmentsControllerListPathParams["transactionId"],
) {
	const res = {
		method: "GET",
		url: `/v1/transactions/${transactionId}/attachments` as const,
	};
	return res;
}

/**
 * {@link /v1/transactions/:transactionId/attachments}
 */
export async function transactionAttachmentsControllerList(
	transactionId: TransactionAttachmentsControllerListPathParams["transactionId"],
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		TransactionAttachmentsControllerListQueryResponse,
		ResponseErrorConfig<TransactionAttachmentsControllerList404>,
		unknown
	>({
		method: "GET",
		url: getTransactionAttachmentsControllerListUrl(transactionId).url.toString(),
		...requestConfig,
	});
	return res.data;
}
