/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	TransactionAttachmentsControllerUploadOptions,
	TransactionAttachmentsControllerUploadResponses,
} from "../schemas/attachments/TransactionAttachmentsControllerUpload";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/transactions/:transactionId/attachments}
 */
export function transactionAttachmentsControllerUpload<
	ThrowOnError extends boolean = true,
>(
	options: Options<TransactionAttachmentsControllerUploadOptions, ThrowOnError>,
): Promise<
	UnwrappedResult<TransactionAttachmentsControllerUploadResponses, ThrowOnError>
> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "POST",
			url: "/v1/transactions/{transactionId}/attachments",
			security: [{ type: "http", scheme: "bearer" }],
			contentType: { request: "multipart/form-data" },
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<
			TransactionAttachmentsControllerUploadResponses,
			ThrowOnError
		>
	>;
}
