/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	AuthControllerLoginOptions,
	AuthControllerLoginResponses,
} from "../schemas/auth/AuthControllerLogin";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/auth/login}
 */
export function authControllerLogin<ThrowOnError extends boolean = true>(
	options: Options<AuthControllerLoginOptions, ThrowOnError>,
): Promise<UnwrappedResult<AuthControllerLoginResponses, ThrowOnError>> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "POST",
			url: "/v1/auth/login",
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<UnwrappedResult<AuthControllerLoginResponses, ThrowOnError>>;
}
