/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	AuthControllerLogoutOptions,
	AuthControllerLogoutResponses,
} from "../schemas/auth/AuthControllerLogout";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/auth/logout}
 */
export function authControllerLogout<ThrowOnError extends boolean = true>(
	options: Options<AuthControllerLogoutOptions, ThrowOnError> = {},
): Promise<UnwrappedResult<AuthControllerLogoutResponses, ThrowOnError>> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "POST",
			url: "/v1/auth/logout",
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<UnwrappedResult<AuthControllerLogoutResponses, ThrowOnError>>;
}
