/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	AuthControllerResetPasswordOptions,
	AuthControllerResetPasswordResponses,
} from "../schemas/auth/AuthControllerResetPassword";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/auth/reset-password}
 */
export function authControllerResetPassword<
	ThrowOnError extends boolean = true,
>(
	options: Options<AuthControllerResetPasswordOptions, ThrowOnError>,
): Promise<
	UnwrappedResult<AuthControllerResetPasswordResponses, ThrowOnError>
> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "POST",
			url: "/v1/auth/reset-password",
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<AuthControllerResetPasswordResponses, ThrowOnError>
	>;
}
