/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	AuthControllerRegisterMutationRequest,
	AuthControllerRegisterMutationResponse,
	AuthControllerRegister409,
} from "../schemas/auth/auth-controller-register.ts";

function getAuthControllerRegisterUrl() {
	const res = { method: "POST", url: `/v1/auth/register` as const };
	return res;
}

/**
 * {@link /v1/auth/register}
 */
export async function authControllerRegister(
	data: AuthControllerRegisterMutationRequest,
	config: Partial<RequestConfig<AuthControllerRegisterMutationRequest>> & {
		client?: Client;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		AuthControllerRegisterMutationResponse,
		ResponseErrorConfig<AuthControllerRegister409>,
		AuthControllerRegisterMutationRequest
	>({
		method: "POST",
		url: getAuthControllerRegisterUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
