/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	AuthControllerRegisterOptions,
	AuthControllerRegisterResponses,
} from "../schemas/auth/AuthControllerRegister";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/auth/register}
 */
export function authControllerRegister<ThrowOnError extends boolean = true>(
	options: Options<AuthControllerRegisterOptions, ThrowOnError>,
): Promise<UnwrappedResult<AuthControllerRegisterResponses, ThrowOnError>> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "POST",
			url: "/v1/auth/register",
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<UnwrappedResult<AuthControllerRegisterResponses, ThrowOnError>>;
}
