/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	AuthControllerForgotPasswordOptions,
	AuthControllerForgotPasswordResponses,
} from "../schemas/auth/AuthControllerForgotPassword";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/auth/forgot-password}
 */
export function authControllerForgotPassword<
	ThrowOnError extends boolean = true,
>(
	options: Options<AuthControllerForgotPasswordOptions, ThrowOnError>,
): Promise<
	UnwrappedResult<AuthControllerForgotPasswordResponses, ThrowOnError>
> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "POST",
			url: "/v1/auth/forgot-password",
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<AuthControllerForgotPasswordResponses, ThrowOnError>
	>;
}
