/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	AuthControllerMeOptions,
	AuthControllerMeResponses,
} from "../schemas/auth/AuthControllerMe";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/auth/me}
 */
export function authControllerMe<ThrowOnError extends boolean = true>(
	options: Options<AuthControllerMeOptions, ThrowOnError> = {},
): Promise<UnwrappedResult<AuthControllerMeResponses, ThrowOnError>> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "GET",
			url: "/v1/auth/me",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<UnwrappedResult<AuthControllerMeResponses, ThrowOnError>>;
}
