/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	DashboardControllerGetSummaryOptions,
	DashboardControllerGetSummaryResponses,
} from "../schemas/dashboard/DashboardControllerGetSummary";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/dashboard}
 */
export function dashboardControllerGetSummary<
	ThrowOnError extends boolean = true,
>(
	options: Options<DashboardControllerGetSummaryOptions, ThrowOnError> = {},
): Promise<
	UnwrappedResult<DashboardControllerGetSummaryResponses, ThrowOnError>
> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "GET",
			url: "/v1/dashboard",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<DashboardControllerGetSummaryResponses, ThrowOnError>
	>;
}
