/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	CategoriesControllerRemoveOptions,
	CategoriesControllerRemoveResponses,
} from "../schemas/categories/CategoriesControllerRemove";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/categories/:id}
 */
export function categoriesControllerRemove<ThrowOnError extends boolean = true>(
	options: Options<CategoriesControllerRemoveOptions, ThrowOnError>,
): Promise<UnwrappedResult<CategoriesControllerRemoveResponses, ThrowOnError>> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "DELETE",
			url: "/v1/categories/{id}",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<CategoriesControllerRemoveResponses, ThrowOnError>
	>;
}
