/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	CategoriesControllerListOptions,
	CategoriesControllerListResponses,
} from "../schemas/categories/CategoriesControllerList";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/categories}
 */
export function categoriesControllerList<ThrowOnError extends boolean = true>(
	options: Options<CategoriesControllerListOptions, ThrowOnError> = {},
): Promise<UnwrappedResult<CategoriesControllerListResponses, ThrowOnError>> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "GET",
			url: "/v1/categories",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<CategoriesControllerListResponses, ThrowOnError>
	>;
}
