/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	CategoriesControllerCreateOptions,
	CategoriesControllerCreateResponses,
} from "../schemas/categories/CategoriesControllerCreate";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/categories}
 */
export function categoriesControllerCreate<ThrowOnError extends boolean = true>(
	options: Options<CategoriesControllerCreateOptions, ThrowOnError>,
): Promise<UnwrappedResult<CategoriesControllerCreateResponses, ThrowOnError>> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "POST",
			url: "/v1/categories",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<CategoriesControllerCreateResponses, ThrowOnError>
	>;
}
