/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	CategoriesControllerUpdateOptions,
	CategoriesControllerUpdateResponses,
} from "../schemas/categories/CategoriesControllerUpdate";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/categories/:id}
 */
export function categoriesControllerUpdate<ThrowOnError extends boolean = true>(
	options: Options<CategoriesControllerUpdateOptions, ThrowOnError>,
): Promise<UnwrappedResult<CategoriesControllerUpdateResponses, ThrowOnError>> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "PUT",
			url: "/v1/categories/{id}",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<CategoriesControllerUpdateResponses, ThrowOnError>
	>;
}
