/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HealthResponseDto } from "../health-response-dto.ts";

export type AppControllerGetHealth200 = HealthResponseDto;

export type AppControllerGetHealthQueryResponse = AppControllerGetHealth200;

export type AppControllerGetHealthQuery = {
	Response: AppControllerGetHealth200;
	Errors: any;
};
