/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HealthResponseDto } from "../HealthResponseDto";

export type AppControllerGetHealthStatus200 = HealthResponseDto;

export type AppControllerGetHealthOptions = {
	body?: never;
	path?: never;
	query?: never;
	headers?: never;
};

export type AppControllerGetHealthResponses = {
	"200": AppControllerGetHealthStatus200;
};

/**
 * @description Union of all possible responses
 */
export type AppControllerGetHealthResponse = AppControllerGetHealthStatus200;
