/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { UsersControllerAcceptPrivacyMutationResponse } from "../../schemas/users/users-controller-accept-privacy.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { usersControllerAcceptPrivacy } from "../users-controller-accept-privacy.ts";

export const usersControllerAcceptPrivacyMutationKey = () =>
	[{ url: "/v1/users/me/privacy-consent" }] as const;

export type UsersControllerAcceptPrivacyMutationKey = ReturnType<
	typeof usersControllerAcceptPrivacyMutationKey
>;

export function usersControllerAcceptPrivacyMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const mutationKey = usersControllerAcceptPrivacyMutationKey();
	return mutationOptions<
		UsersControllerAcceptPrivacyMutationResponse,
		ResponseErrorConfig<Error>,
		void,
		TContext
	>({
		mutationKey,
		mutationFn: async () => {
			return usersControllerAcceptPrivacy(config);
		},
	});
}

/**
 * {@link /v1/users/me/privacy-consent}
 */
export function useUsersControllerAcceptPrivacy<TContext>(
	options: {
		mutation?: UseMutationOptions<
			UsersControllerAcceptPrivacyMutationResponse,
			ResponseErrorConfig<Error>,
			void,
			TContext
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? usersControllerAcceptPrivacyMutationKey();

	const baseOptions = usersControllerAcceptPrivacyMutationOptions(
		config,
	) as UseMutationOptions<
		UsersControllerAcceptPrivacyMutationResponse,
		ResponseErrorConfig<Error>,
		void,
		TContext
	>;

	return useMutation<
		UsersControllerAcceptPrivacyMutationResponse,
		ResponseErrorConfig<Error>,
		void,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		UsersControllerAcceptPrivacyMutationResponse,
		ResponseErrorConfig<Error>,
		void,
		TContext
	>;
}
