/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type {
	UsersControllerDeleteOwnAccountMutationRequest,
	UsersControllerDeleteOwnAccountMutationResponse,
	UsersControllerDeleteOwnAccount401,
} from "../../schemas/users/users-controller-delete-own-account.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { usersControllerDeleteOwnAccount } from "../users-controller-delete-own-account.ts";

export const usersControllerDeleteOwnAccountMutationKey = () =>
	[{ url: "/v1/users/me" }] as const;

export type UsersControllerDeleteOwnAccountMutationKey = ReturnType<
	typeof usersControllerDeleteOwnAccountMutationKey
>;

export function usersControllerDeleteOwnAccountMutationOptions<
	TContext = unknown,
>(
	config: Partial<
		RequestConfig<UsersControllerDeleteOwnAccountMutationRequest>
	> & { client?: Client } = {},
) {
	const mutationKey = usersControllerDeleteOwnAccountMutationKey();
	return mutationOptions<
		UsersControllerDeleteOwnAccountMutationResponse,
		ResponseErrorConfig<UsersControllerDeleteOwnAccount401>,
		{ data: UsersControllerDeleteOwnAccountMutationRequest },
		TContext
	>({
		mutationKey,
		mutationFn: async ({ data }) => {
			return usersControllerDeleteOwnAccount(data, config);
		},
	});
}

/**
 * {@link /v1/users/me}
 */
export function useUsersControllerDeleteOwnAccount<TContext>(
	options: {
		mutation?: UseMutationOptions<
			UsersControllerDeleteOwnAccountMutationResponse,
			ResponseErrorConfig<UsersControllerDeleteOwnAccount401>,
			{ data: UsersControllerDeleteOwnAccountMutationRequest },
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			RequestConfig<UsersControllerDeleteOwnAccountMutationRequest>
		> & { client?: Client };
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? usersControllerDeleteOwnAccountMutationKey();

	const baseOptions = usersControllerDeleteOwnAccountMutationOptions(
		config,
	) as UseMutationOptions<
		UsersControllerDeleteOwnAccountMutationResponse,
		ResponseErrorConfig<UsersControllerDeleteOwnAccount401>,
		{ data: UsersControllerDeleteOwnAccountMutationRequest },
		TContext
	>;

	return useMutation<
		UsersControllerDeleteOwnAccountMutationResponse,
		ResponseErrorConfig<UsersControllerDeleteOwnAccount401>,
		{ data: UsersControllerDeleteOwnAccountMutationRequest },
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		UsersControllerDeleteOwnAccountMutationResponse,
		ResponseErrorConfig<UsersControllerDeleteOwnAccount401>,
		{ data: UsersControllerDeleteOwnAccountMutationRequest },
		TContext
	>;
}
