/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type { UsersControllerAcceptPrivacyStatus200 } from "../../schemas/users/UsersControllerAcceptPrivacy";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { usersControllerAcceptPrivacy } from "../usersControllerAcceptPrivacy";

export const usersControllerAcceptPrivacyMutationKey = () =>
	[{ url: "/v1/users/me/privacy-consent" }] as const;

export function usersControllerAcceptPrivacyMutationOptions<TContext = unknown>(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const mutationKey = usersControllerAcceptPrivacyMutationKey();
	return mutationOptions<
		UsersControllerAcceptPrivacyStatus200,
		ResponseErrorConfig<Error>,
		undefined,
		TContext
	>({
		mutationKey,
		mutationFn: async (_) => {
			return await usersControllerAcceptPrivacy({
				...config,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/users/me/privacy-consent}
 */
export function useUsersControllerAcceptPrivacy<TContext>(
	options: {
		mutation?: UseMutationOptions<
			UsersControllerAcceptPrivacyStatus200,
			ResponseErrorConfig<Error>,
			undefined,
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? usersControllerAcceptPrivacyMutationKey();

	const baseOptions = usersControllerAcceptPrivacyMutationOptions(
		config,
	) as UseMutationOptions<
		UsersControllerAcceptPrivacyStatus200,
		ResponseErrorConfig<Error>,
		undefined,
		TContext
	>;

	return useMutation<
		UsersControllerAcceptPrivacyStatus200,
		ResponseErrorConfig<Error>,
		undefined,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		UsersControllerAcceptPrivacyStatus200,
		ResponseErrorConfig<Error>,
		undefined,
		TContext
	>;
}
