/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	UsersControllerUpdateOwnProfileOptions,
	UsersControllerUpdateOwnProfileStatus200,
	UsersControllerUpdateOwnProfileStatus401,
	UsersControllerUpdateOwnProfileStatus409,
} from "../../schemas/users/UsersControllerUpdateOwnProfile";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { usersControllerUpdateOwnProfile } from "../usersControllerUpdateOwnProfile";

export const usersControllerUpdateOwnProfileMutationKey = () =>
	[{ url: "/v1/users/me" }] as const;

export function usersControllerUpdateOwnProfileMutationOptions<
	TContext = unknown,
>(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const mutationKey = usersControllerUpdateOwnProfileMutationKey();
	return mutationOptions<
		UsersControllerUpdateOwnProfileStatus200,
		ResponseErrorConfig<
			| UsersControllerUpdateOwnProfileStatus401
			| UsersControllerUpdateOwnProfileStatus409
		>,
		UsersControllerUpdateOwnProfileOptions,
		TContext
	>({
		mutationKey,
		mutationFn: async ({ body }) => {
			return await usersControllerUpdateOwnProfile({
				...config,
				body,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/users/me}
 */
export function useUsersControllerUpdateOwnProfile<TContext>(
	options: {
		mutation?: UseMutationOptions<
			UsersControllerUpdateOwnProfileStatus200,
			ResponseErrorConfig<
				| UsersControllerUpdateOwnProfileStatus401
				| UsersControllerUpdateOwnProfileStatus409
			>,
			UsersControllerUpdateOwnProfileOptions,
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? usersControllerUpdateOwnProfileMutationKey();

	const baseOptions = usersControllerUpdateOwnProfileMutationOptions(
		config,
	) as UseMutationOptions<
		UsersControllerUpdateOwnProfileStatus200,
		ResponseErrorConfig<
			| UsersControllerUpdateOwnProfileStatus401
			| UsersControllerUpdateOwnProfileStatus409
		>,
		UsersControllerUpdateOwnProfileOptions,
		TContext
	>;

	return useMutation<
		UsersControllerUpdateOwnProfileStatus200,
		ResponseErrorConfig<
			| UsersControllerUpdateOwnProfileStatus401
			| UsersControllerUpdateOwnProfileStatus409
		>,
		UsersControllerUpdateOwnProfileOptions,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		UsersControllerUpdateOwnProfileStatus200,
		ResponseErrorConfig<
			| UsersControllerUpdateOwnProfileStatus401
			| UsersControllerUpdateOwnProfileStatus409
		>,
		UsersControllerUpdateOwnProfileOptions,
		TContext
	>;
}
