/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	UsersControllerUpdateByAdminOptions,
	UsersControllerUpdateByAdminStatus200,
	UsersControllerUpdateByAdminStatus401,
	UsersControllerUpdateByAdminStatus403,
	UsersControllerUpdateByAdminStatus404,
	UsersControllerUpdateByAdminStatus409,
} from "../../schemas/users/UsersControllerUpdateByAdmin";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { usersControllerUpdateByAdmin } from "../usersControllerUpdateByAdmin";

export const usersControllerUpdateByAdminMutationKey = () =>
	[{ url: "/v1/users/:id" }] as const;

export function usersControllerUpdateByAdminMutationOptions<TContext = unknown>(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const mutationKey = usersControllerUpdateByAdminMutationKey();
	return mutationOptions<
		UsersControllerUpdateByAdminStatus200,
		ResponseErrorConfig<
			| UsersControllerUpdateByAdminStatus401
			| UsersControllerUpdateByAdminStatus403
			| UsersControllerUpdateByAdminStatus404
			| UsersControllerUpdateByAdminStatus409
		>,
		UsersControllerUpdateByAdminOptions,
		TContext
	>({
		mutationKey,
		mutationFn: async ({ path, body }) => {
			return await usersControllerUpdateByAdmin({
				...config,
				path,
				body,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/users/:id}
 */
export function useUsersControllerUpdateByAdmin<TContext>(
	options: {
		mutation?: UseMutationOptions<
			UsersControllerUpdateByAdminStatus200,
			ResponseErrorConfig<
				| UsersControllerUpdateByAdminStatus401
				| UsersControllerUpdateByAdminStatus403
				| UsersControllerUpdateByAdminStatus404
				| UsersControllerUpdateByAdminStatus409
			>,
			UsersControllerUpdateByAdminOptions,
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? usersControllerUpdateByAdminMutationKey();

	const baseOptions = usersControllerUpdateByAdminMutationOptions(
		config,
	) as UseMutationOptions<
		UsersControllerUpdateByAdminStatus200,
		ResponseErrorConfig<
			| UsersControllerUpdateByAdminStatus401
			| UsersControllerUpdateByAdminStatus403
			| UsersControllerUpdateByAdminStatus404
			| UsersControllerUpdateByAdminStatus409
		>,
		UsersControllerUpdateByAdminOptions,
		TContext
	>;

	return useMutation<
		UsersControllerUpdateByAdminStatus200,
		ResponseErrorConfig<
			| UsersControllerUpdateByAdminStatus401
			| UsersControllerUpdateByAdminStatus403
			| UsersControllerUpdateByAdminStatus404
			| UsersControllerUpdateByAdminStatus409
		>,
		UsersControllerUpdateByAdminOptions,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		UsersControllerUpdateByAdminStatus200,
		ResponseErrorConfig<
			| UsersControllerUpdateByAdminStatus401
			| UsersControllerUpdateByAdminStatus403
			| UsersControllerUpdateByAdminStatus404
			| UsersControllerUpdateByAdminStatus409
		>,
		UsersControllerUpdateByAdminOptions,
		TContext
	>;
}
