/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	UsersControllerAdminResetPasswordOptions,
	UsersControllerAdminResetPasswordStatus200,
	UsersControllerAdminResetPasswordStatus401,
	UsersControllerAdminResetPasswordStatus403,
	UsersControllerAdminResetPasswordStatus404,
} from "../../schemas/users/UsersControllerAdminResetPassword";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { usersControllerAdminResetPassword } from "../usersControllerAdminResetPassword";

export const usersControllerAdminResetPasswordMutationKey = () =>
	[{ url: "/v1/users/:id/password" }] as const;

export function usersControllerAdminResetPasswordMutationOptions<
	TContext = unknown,
>(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const mutationKey = usersControllerAdminResetPasswordMutationKey();
	return mutationOptions<
		UsersControllerAdminResetPasswordStatus200,
		ResponseErrorConfig<
			| UsersControllerAdminResetPasswordStatus401
			| UsersControllerAdminResetPasswordStatus403
			| UsersControllerAdminResetPasswordStatus404
		>,
		UsersControllerAdminResetPasswordOptions,
		TContext
	>({
		mutationKey,
		mutationFn: async ({ path, body }) => {
			return await usersControllerAdminResetPassword({
				...config,
				path,
				body,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/users/:id/password}
 */
export function useUsersControllerAdminResetPassword<TContext>(
	options: {
		mutation?: UseMutationOptions<
			UsersControllerAdminResetPasswordStatus200,
			ResponseErrorConfig<
				| UsersControllerAdminResetPasswordStatus401
				| UsersControllerAdminResetPasswordStatus403
				| UsersControllerAdminResetPasswordStatus404
			>,
			UsersControllerAdminResetPasswordOptions,
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ??
		usersControllerAdminResetPasswordMutationKey();

	const baseOptions = usersControllerAdminResetPasswordMutationOptions(
		config,
	) as UseMutationOptions<
		UsersControllerAdminResetPasswordStatus200,
		ResponseErrorConfig<
			| UsersControllerAdminResetPasswordStatus401
			| UsersControllerAdminResetPasswordStatus403
			| UsersControllerAdminResetPasswordStatus404
		>,
		UsersControllerAdminResetPasswordOptions,
		TContext
	>;

	return useMutation<
		UsersControllerAdminResetPasswordStatus200,
		ResponseErrorConfig<
			| UsersControllerAdminResetPasswordStatus401
			| UsersControllerAdminResetPasswordStatus403
			| UsersControllerAdminResetPasswordStatus404
		>,
		UsersControllerAdminResetPasswordOptions,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		UsersControllerAdminResetPasswordStatus200,
		ResponseErrorConfig<
			| UsersControllerAdminResetPasswordStatus401
			| UsersControllerAdminResetPasswordStatus403
			| UsersControllerAdminResetPasswordStatus404
		>,
		UsersControllerAdminResetPasswordOptions,
		TContext
	>;
}
