/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	UsersControllerDeleteOwnAccountOptions,
	UsersControllerDeleteOwnAccountStatus200,
	UsersControllerDeleteOwnAccountStatus403,
} from "../../schemas/users/UsersControllerDeleteOwnAccount";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { usersControllerDeleteOwnAccount } from "../usersControllerDeleteOwnAccount";

export const usersControllerDeleteOwnAccountMutationKey = () =>
	[{ url: "/v1/users/me" }] as const;

export function usersControllerDeleteOwnAccountMutationOptions<
	TContext = unknown,
>(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const mutationKey = usersControllerDeleteOwnAccountMutationKey();
	return mutationOptions<
		UsersControllerDeleteOwnAccountStatus200,
		ResponseErrorConfig<UsersControllerDeleteOwnAccountStatus403>,
		UsersControllerDeleteOwnAccountOptions,
		TContext
	>({
		mutationKey,
		mutationFn: async ({ body }) => {
			return await usersControllerDeleteOwnAccount({
				...config,
				body,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/users/me}
 */
export function useUsersControllerDeleteOwnAccount<TContext>(
	options: {
		mutation?: UseMutationOptions<
			UsersControllerDeleteOwnAccountStatus200,
			ResponseErrorConfig<UsersControllerDeleteOwnAccountStatus403>,
			UsersControllerDeleteOwnAccountOptions,
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? usersControllerDeleteOwnAccountMutationKey();

	const baseOptions = usersControllerDeleteOwnAccountMutationOptions(
		config,
	) as UseMutationOptions<
		UsersControllerDeleteOwnAccountStatus200,
		ResponseErrorConfig<UsersControllerDeleteOwnAccountStatus403>,
		UsersControllerDeleteOwnAccountOptions,
		TContext
	>;

	return useMutation<
		UsersControllerDeleteOwnAccountStatus200,
		ResponseErrorConfig<UsersControllerDeleteOwnAccountStatus403>,
		UsersControllerDeleteOwnAccountOptions,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		UsersControllerDeleteOwnAccountStatus200,
		ResponseErrorConfig<UsersControllerDeleteOwnAccountStatus403>,
		UsersControllerDeleteOwnAccountOptions,
		TContext
	>;
}
