/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	UsersControllerCreateOptions,
	UsersControllerCreateStatus201,
	UsersControllerCreateStatus401,
	UsersControllerCreateStatus403,
	UsersControllerCreateStatus409,
} from "../../schemas/users/UsersControllerCreate";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { usersControllerCreate } from "../usersControllerCreate";

export const usersControllerCreateMutationKey = () =>
	[{ url: "/v1/users" }] as const;

export function usersControllerCreateMutationOptions<TContext = unknown>(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const mutationKey = usersControllerCreateMutationKey();
	return mutationOptions<
		UsersControllerCreateStatus201,
		ResponseErrorConfig<
			| UsersControllerCreateStatus401
			| UsersControllerCreateStatus403
			| UsersControllerCreateStatus409
		>,
		UsersControllerCreateOptions,
		TContext
	>({
		mutationKey,
		mutationFn: async ({ body }) => {
			return await usersControllerCreate({
				...config,
				body,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/users}
 */
export function useUsersControllerCreate<TContext>(
	options: {
		mutation?: UseMutationOptions<
			UsersControllerCreateStatus201,
			ResponseErrorConfig<
				| UsersControllerCreateStatus401
				| UsersControllerCreateStatus403
				| UsersControllerCreateStatus409
			>,
			UsersControllerCreateOptions,
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? usersControllerCreateMutationKey();

	const baseOptions = usersControllerCreateMutationOptions(
		config,
	) as UseMutationOptions<
		UsersControllerCreateStatus201,
		ResponseErrorConfig<
			| UsersControllerCreateStatus401
			| UsersControllerCreateStatus403
			| UsersControllerCreateStatus409
		>,
		UsersControllerCreateOptions,
		TContext
	>;

	return useMutation<
		UsersControllerCreateStatus201,
		ResponseErrorConfig<
			| UsersControllerCreateStatus401
			| UsersControllerCreateStatus403
			| UsersControllerCreateStatus409
		>,
		UsersControllerCreateOptions,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		UsersControllerCreateStatus201,
		ResponseErrorConfig<
			| UsersControllerCreateStatus401
			| UsersControllerCreateStatus403
			| UsersControllerCreateStatus409
		>,
		UsersControllerCreateOptions,
		TContext
	>;
}
