/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	UsersControllerListOptions,
	UsersControllerListStatus200,
	UsersControllerListStatus401,
	UsersControllerListStatus403,
} from "../../schemas/users/UsersControllerList";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { usersControllerList } from "../usersControllerList";

export const usersControllerListQueryKey = ({
	query,
}: Omit<UsersControllerListOptions, "headers"> = {}) =>
	[{ url: "/v1/users" }, ...(query ? [query] : [])] as const;

type UsersControllerListQueryKey = ReturnType<
	typeof usersControllerListQueryKey
>;

export function usersControllerListQueryOptions(
	{ query }: UsersControllerListOptions = {},
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const queryKey = usersControllerListQueryKey({ query });
	return queryOptions<
		UsersControllerListStatus200,
		ResponseErrorConfig<
			UsersControllerListStatus401 | UsersControllerListStatus403
		>,
		UsersControllerListStatus200,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return await usersControllerList({
				...config,
				query,
				signal: config.signal ?? signal,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/users}
 */
export function useUsersControllerList<
	TData = UsersControllerListStatus200,
	TQueryData = UsersControllerListStatus200,
	TQueryKey extends QueryKey = UsersControllerListQueryKey,
>(
	{
		query,
	}: {
		query?:
			| UsersControllerListOptions["query"]
			| (() => UsersControllerListOptions["query"]);
	} = {},
	options: {
		query?: Partial<
			QueryObserverOptions<
				UsersControllerListStatus200,
				ResponseErrorConfig<
					UsersControllerListStatus401 | UsersControllerListStatus403
				>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const resolvedParams = {
		query: typeof query === "function" ? query() : query,
	};
	const queryKey =
		resolvedOptions?.queryKey ?? usersControllerListQueryKey(resolvedParams);

	const queryResult = useQuery(
		{
			...usersControllerListQueryOptions(resolvedParams, config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<
		TData,
		ResponseErrorConfig<
			UsersControllerListStatus401 | UsersControllerListStatus403
		>
	> & { queryKey: TQueryKey };

	queryResult.queryKey = queryKey as TQueryKey;

	return queryResult;
}
