/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UpdateOwnProfileDto } from "../UpdateOwnProfileDto";
import type { UserResponseDto } from "../UserResponseDto";

export type UsersControllerUpdateOwnProfileStatus200 = UserResponseDto;

export type UsersControllerUpdateOwnProfileStatus401 = unknown;

export type UsersControllerUpdateOwnProfileStatus409 = unknown;

export type UsersControllerUpdateOwnProfileBody = UpdateOwnProfileDto;

export type UsersControllerUpdateOwnProfileOptions = {
	body: UsersControllerUpdateOwnProfileBody;
	path?: never;
	query?: never;
	headers?: never;
};

export type UsersControllerUpdateOwnProfileResponses = {
	"200": UsersControllerUpdateOwnProfileStatus200;
	"401": UsersControllerUpdateOwnProfileStatus401;
	"409": UsersControllerUpdateOwnProfileStatus409;
};

/**
 * @description Union of all possible responses
 */
export type UsersControllerUpdateOwnProfileResponse =
	UsersControllerUpdateOwnProfileStatus200;
