/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AdminResetPasswordDto } from "../admin-reset-password-dto.ts";
import type { SuccessResponseDto } from "../success-response-dto.ts";

export type UsersControllerAdminResetPasswordPathParams = {
	/**
	 * @type string
	 */
	id: string;
};

export type UsersControllerAdminResetPassword200 = SuccessResponseDto;

/**
 * @description Não autenticado
 */
export type UsersControllerAdminResetPassword401 = any;

/**
 * @description Sem permissão para executar esta ação
 */
export type UsersControllerAdminResetPassword403 = any;

/**
 * @description Usuário não encontrado
 */
export type UsersControllerAdminResetPassword404 = any;

export type UsersControllerAdminResetPasswordMutationRequest =
	AdminResetPasswordDto;

export type UsersControllerAdminResetPasswordMutationResponse =
	UsersControllerAdminResetPassword200;

export type UsersControllerAdminResetPasswordMutation = {
	Response: UsersControllerAdminResetPassword200;
	Request: UsersControllerAdminResetPasswordMutationRequest;
	PathParams: UsersControllerAdminResetPasswordPathParams;
	Errors:
		| UsersControllerAdminResetPassword401
		| UsersControllerAdminResetPassword403
		| UsersControllerAdminResetPassword404;
};
