/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DeleteOwnAccountDto } from "../DeleteOwnAccountDto";
import type { SuccessResponseDto } from "../SuccessResponseDto";

export type UsersControllerDeleteOwnAccountStatus200 = SuccessResponseDto;

export type UsersControllerDeleteOwnAccountStatus403 = unknown;

export type UsersControllerDeleteOwnAccountBody = DeleteOwnAccountDto;

export type UsersControllerDeleteOwnAccountOptions = {
	body: UsersControllerDeleteOwnAccountBody;
	path?: never;
	query?: never;
	headers?: never;
};

export type UsersControllerDeleteOwnAccountResponses = {
	"200": UsersControllerDeleteOwnAccountStatus200;
	"403": UsersControllerDeleteOwnAccountStatus403;
};

/**
 * @description Union of all possible responses
 */
export type UsersControllerDeleteOwnAccountResponse =
	UsersControllerDeleteOwnAccountStatus200;
