/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { SuccessResponseDto } from "../success-response-dto.ts";

export type UsersControllerAcceptPrivacy200 = SuccessResponseDto;

export type UsersControllerAcceptPrivacyMutationResponse =
	UsersControllerAcceptPrivacy200;

export type UsersControllerAcceptPrivacyMutation = {
	Response: UsersControllerAcceptPrivacy200;
	Errors: any;
};
