/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { SuccessResponseDto } from "../SuccessResponseDto";

export type UsersControllerAcceptPrivacyStatus200 = SuccessResponseDto;

export type UsersControllerAcceptPrivacyOptions = {
	body?: never;
	path?: never;
	query?: never;
	headers?: never;
};

export type UsersControllerAcceptPrivacyResponses = {
	"200": UsersControllerAcceptPrivacyStatus200;
};

/**
 * @description Union of all possible responses
 */
export type UsersControllerAcceptPrivacyResponse =
	UsersControllerAcceptPrivacyStatus200;
