/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateUserDto } from "../CreateUserDto";
import type { UserResponseDto } from "../UserResponseDto";

export type UsersControllerCreateStatus201 = UserResponseDto;

export type UsersControllerCreateStatus401 = unknown;

export type UsersControllerCreateStatus403 = unknown;

export type UsersControllerCreateStatus409 = unknown;

export type UsersControllerCreateBody = CreateUserDto;

export type UsersControllerCreateOptions = {
	body: UsersControllerCreateBody;
	path?: never;
	query?: never;
	headers?: never;
};

export type UsersControllerCreateResponses = {
	"201": UsersControllerCreateStatus201;
	"401": UsersControllerCreateStatus401;
	"403": UsersControllerCreateStatus403;
	"409": UsersControllerCreateStatus409;
};

/**
 * @description Union of all possible responses
 */
export type UsersControllerCreateResponse = UsersControllerCreateStatus201;
