/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UpdateUserByAdminDto } from "../UpdateUserByAdminDto";
import type { UserResponseDto } from "../UserResponseDto";

export type UsersControllerUpdateByAdminPath = {
	id: string;
};

export type UsersControllerUpdateByAdminStatus200 = UserResponseDto;

export type UsersControllerUpdateByAdminStatus401 = unknown;

export type UsersControllerUpdateByAdminStatus403 = unknown;

export type UsersControllerUpdateByAdminStatus404 = unknown;

export type UsersControllerUpdateByAdminStatus409 = unknown;

export type UsersControllerUpdateByAdminBody = UpdateUserByAdminDto;

export type UsersControllerUpdateByAdminOptions = {
	body: UsersControllerUpdateByAdminBody;
	path: UsersControllerUpdateByAdminPath;
	query?: never;
	headers?: never;
};

export type UsersControllerUpdateByAdminResponses = {
	"200": UsersControllerUpdateByAdminStatus200;
	"401": UsersControllerUpdateByAdminStatus401;
	"403": UsersControllerUpdateByAdminStatus403;
	"404": UsersControllerUpdateByAdminStatus404;
	"409": UsersControllerUpdateByAdminStatus409;
};

/**
 * @description Union of all possible responses
 */
export type UsersControllerUpdateByAdminResponse =
	UsersControllerUpdateByAdminStatus200;
