/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AdminResetPasswordDto } from "../AdminResetPasswordDto";
import type { SuccessResponseDto } from "../SuccessResponseDto";

export type UsersControllerAdminResetPasswordPath = {
	id: string;
};

export type UsersControllerAdminResetPasswordStatus200 = SuccessResponseDto;

export type UsersControllerAdminResetPasswordStatus401 = unknown;

export type UsersControllerAdminResetPasswordStatus403 = unknown;

export type UsersControllerAdminResetPasswordStatus404 = unknown;

export type UsersControllerAdminResetPasswordBody = AdminResetPasswordDto;

export type UsersControllerAdminResetPasswordOptions = {
	body: UsersControllerAdminResetPasswordBody;
	path: UsersControllerAdminResetPasswordPath;
	query?: never;
	headers?: never;
};

export type UsersControllerAdminResetPasswordResponses = {
	"200": UsersControllerAdminResetPasswordStatus200;
	"401": UsersControllerAdminResetPasswordStatus401;
	"403": UsersControllerAdminResetPasswordStatus403;
	"404": UsersControllerAdminResetPasswordStatus404;
};

/**
 * @description Union of all possible responses
 */
export type UsersControllerAdminResetPasswordResponse =
	UsersControllerAdminResetPasswordStatus200;
