/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ListUsersResponseDto } from "../ListUsersResponseDto";

export type UsersControllerListQuery = {
	/**
	 * @minLength 1
	 * @default 1
	 * @example 1
	 * @type number | undefined
	 */
	page?: number;
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @default 10
	 * @example 10
	 * @type number | undefined
	 */
	perPage?: number;
	/**
	 * @description Busca por nome ou e-mail
	 * @example maria@empresa.com
	 * @type string | undefined
	 */
	search?: string;
};

export type UsersControllerListStatus200 = ListUsersResponseDto;

export type UsersControllerListStatus401 = unknown;

export type UsersControllerListStatus403 = unknown;

export type UsersControllerListOptions = {
	body?: never;
	path?: never;
	query?: UsersControllerListQuery;
	headers?: never;
};

export type UsersControllerListResponses = {
	"200": UsersControllerListStatus200;
	"401": UsersControllerListStatus401;
	"403": UsersControllerListStatus403;
};

/**
 * @description Union of all possible responses
 */
export type UsersControllerListResponse = UsersControllerListStatus200;
