/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UsersControllerDeleteOwnAccountMutationRequest,
	UsersControllerDeleteOwnAccountMutationResponse,
	UsersControllerDeleteOwnAccount401,
} from "../schemas/users/users-controller-delete-own-account.ts";

function getUsersControllerDeleteOwnAccountUrl() {
	const res = { method: "DELETE", url: `/v1/users/me` as const };
	return res;
}

/**
 * {@link /v1/users/me}
 */
export async function usersControllerDeleteOwnAccount(
	data: UsersControllerDeleteOwnAccountMutationRequest,
	config: Partial<
		RequestConfig<UsersControllerDeleteOwnAccountMutationRequest>
	> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		UsersControllerDeleteOwnAccountMutationResponse,
		ResponseErrorConfig<UsersControllerDeleteOwnAccount401>,
		UsersControllerDeleteOwnAccountMutationRequest
	>({
		method: "DELETE",
		url: getUsersControllerDeleteOwnAccountUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
