/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	UsersControllerAcceptPrivacyOptions,
	UsersControllerAcceptPrivacyResponses,
} from "../schemas/users/UsersControllerAcceptPrivacy";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/users/me/privacy-consent}
 */
export function usersControllerAcceptPrivacy<
	ThrowOnError extends boolean = true,
>(
	options: Options<UsersControllerAcceptPrivacyOptions, ThrowOnError> = {},
): Promise<
	UnwrappedResult<UsersControllerAcceptPrivacyResponses, ThrowOnError>
> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "POST",
			url: "/v1/users/me/privacy-consent",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<UsersControllerAcceptPrivacyResponses, ThrowOnError>
	>;
}
