/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	UsersControllerUpdateOwnProfileOptions,
	UsersControllerUpdateOwnProfileResponses,
} from "../schemas/users/UsersControllerUpdateOwnProfile";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/users/me}
 */
export function usersControllerUpdateOwnProfile<
	ThrowOnError extends boolean = true,
>(
	options: Options<UsersControllerUpdateOwnProfileOptions, ThrowOnError>,
): Promise<
	UnwrappedResult<UsersControllerUpdateOwnProfileResponses, ThrowOnError>
> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "PUT",
			url: "/v1/users/me",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<UsersControllerUpdateOwnProfileResponses, ThrowOnError>
	>;
}
