/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	UsersControllerAdminResetPasswordOptions,
	UsersControllerAdminResetPasswordResponses,
} from "../schemas/users/UsersControllerAdminResetPassword";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/users/:id/password}
 */
export function usersControllerAdminResetPassword<
	ThrowOnError extends boolean = true,
>(
	options: Options<UsersControllerAdminResetPasswordOptions, ThrowOnError>,
): Promise<
	UnwrappedResult<UsersControllerAdminResetPasswordResponses, ThrowOnError>
> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "PUT",
			url: "/v1/users/{id}/password",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<UsersControllerAdminResetPasswordResponses, ThrowOnError>
	>;
}
