/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	UsersControllerCreateOptions,
	UsersControllerCreateResponses,
} from "../schemas/users/UsersControllerCreate";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/users}
 */
export function usersControllerCreate<ThrowOnError extends boolean = true>(
	options: Options<UsersControllerCreateOptions, ThrowOnError>,
): Promise<UnwrappedResult<UsersControllerCreateResponses, ThrowOnError>> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "POST",
			url: "/v1/users",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<UnwrappedResult<UsersControllerCreateResponses, ThrowOnError>>;
}
