/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	UsersControllerUpdateByAdminOptions,
	UsersControllerUpdateByAdminResponses,
} from "../schemas/users/UsersControllerUpdateByAdmin";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/users/:id}
 */
export function usersControllerUpdateByAdmin<
	ThrowOnError extends boolean = true,
>(
	options: Options<UsersControllerUpdateByAdminOptions, ThrowOnError>,
): Promise<
	UnwrappedResult<UsersControllerUpdateByAdminResponses, ThrowOnError>
> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "PUT",
			url: "/v1/users/{id}",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<UsersControllerUpdateByAdminResponses, ThrowOnError>
	>;
}
