/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	UsersControllerListOptions,
	UsersControllerListResponses,
} from "../schemas/users/UsersControllerList";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/users}
 */
export function usersControllerList<ThrowOnError extends boolean = true>(
	options: Options<UsersControllerListOptions, ThrowOnError> = {},
): Promise<UnwrappedResult<UsersControllerListResponses, ThrowOnError>> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "GET",
			url: "/v1/users",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<UnwrappedResult<UsersControllerListResponses, ThrowOnError>>;
}
