/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	UsersControllerDeleteOwnAccountOptions,
	UsersControllerDeleteOwnAccountResponses,
} from "../schemas/users/UsersControllerDeleteOwnAccount";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/users/me}
 */
export function usersControllerDeleteOwnAccount<
	ThrowOnError extends boolean = true,
>(
	options: Options<UsersControllerDeleteOwnAccountOptions, ThrowOnError>,
): Promise<
	UnwrappedResult<UsersControllerDeleteOwnAccountResponses, ThrowOnError>
> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "DELETE",
			url: "/v1/users/me",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<UsersControllerDeleteOwnAccountResponses, ThrowOnError>
	>;
}
