/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type { UsersControllerAcceptPrivacyMutationResponse } from "../schemas/users/users-controller-accept-privacy.ts";

function getUsersControllerAcceptPrivacyUrl() {
	const res = { method: "POST", url: `/v1/users/me/privacy-consent` as const };
	return res;
}

/**
 * {@link /v1/users/me/privacy-consent}
 */
export async function usersControllerAcceptPrivacy(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		UsersControllerAcceptPrivacyMutationResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "POST",
		url: getUsersControllerAcceptPrivacyUrl().url.toString(),
		...requestConfig,
	});
	return res.data;
}
