/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CategoryResponseDto } from "../category-response-dto.ts";

export type CategoriesControllerList200 = CategoryResponseDto[];

/**
 * @description Não autenticado
 */
export type CategoriesControllerList401 = any;

export type CategoriesControllerListQueryResponse = CategoriesControllerList200;

export type CategoriesControllerListQuery = {
	Response: CategoriesControllerList200;
	Errors: CategoriesControllerList401;
};
