/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CategoryListItemDto } from "../category-list-item-dto.ts";

export type CategoriesControllerList200 = CategoryListItemDto[];

/**
 * @description Não autenticado
 */
export type CategoriesControllerList401 = any;

export type CategoriesControllerListQueryResponse = CategoriesControllerList200;

export type CategoriesControllerListQuery = {
	Response: CategoriesControllerList200;
	Errors: CategoriesControllerList401;
};
