/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CategoryListItemDto } from "../CategoryListItemDto";

export type CategoriesControllerListStatus200 = CategoryListItemDto[];

export type CategoriesControllerListStatus401 = unknown;

export type CategoriesControllerListOptions = {
	body?: never;
	path?: never;
	query?: never;
	headers?: never;
};

export type CategoriesControllerListResponses = {
	"200": CategoriesControllerListStatus200;
	"401": CategoriesControllerListStatus401;
};

/**
 * @description Union of all possible responses
 */
export type CategoriesControllerListResponse =
	CategoriesControllerListStatus200;
