/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CategoryResponseDto } from "../CategoryResponseDto";
import type { UpdateCategoryDto } from "../UpdateCategoryDto";

export type CategoriesControllerUpdatePath = {
	id: string;
};

export type CategoriesControllerUpdateStatus200 = CategoryResponseDto;

export type CategoriesControllerUpdateStatus401 = unknown;

export type CategoriesControllerUpdateStatus403 = unknown;

export type CategoriesControllerUpdateStatus404 = unknown;

export type CategoriesControllerUpdateStatus409 = unknown;

export type CategoriesControllerUpdateBody = UpdateCategoryDto;

export type CategoriesControllerUpdateOptions = {
	body: CategoriesControllerUpdateBody;
	path: CategoriesControllerUpdatePath;
	query?: never;
	headers?: never;
};

export type CategoriesControllerUpdateResponses = {
	"200": CategoriesControllerUpdateStatus200;
	"401": CategoriesControllerUpdateStatus401;
	"403": CategoriesControllerUpdateStatus403;
	"404": CategoriesControllerUpdateStatus404;
	"409": CategoriesControllerUpdateStatus409;
};

/**
 * @description Union of all possible responses
 */
export type CategoriesControllerUpdateResponse =
	CategoriesControllerUpdateStatus200;
