/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MessageResponseDto } from "../MessageResponseDto";

export type CategoriesControllerRemovePath = {
	id: string;
};

export type CategoriesControllerRemoveStatus200 = MessageResponseDto;

export type CategoriesControllerRemoveStatus401 = unknown;

export type CategoriesControllerRemoveStatus403 = unknown;

export type CategoriesControllerRemoveStatus404 = unknown;

export type CategoriesControllerRemoveStatus409 = unknown;

export type CategoriesControllerRemoveOptions = {
	body?: never;
	path: CategoriesControllerRemovePath;
	query?: never;
	headers?: never;
};

export type CategoriesControllerRemoveResponses = {
	"200": CategoriesControllerRemoveStatus200;
	"401": CategoriesControllerRemoveStatus401;
	"403": CategoriesControllerRemoveStatus403;
	"404": CategoriesControllerRemoveStatus404;
	"409": CategoriesControllerRemoveStatus409;
};

/**
 * @description Union of all possible responses
 */
export type CategoriesControllerRemoveResponse =
	CategoriesControllerRemoveStatus200;
