/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CategoryResponseDto } from "../CategoryResponseDto";

export type CategoriesControllerGetByIdPath = {
	id: string;
};

export type CategoriesControllerGetByIdStatus200 = CategoryResponseDto;

export type CategoriesControllerGetByIdStatus401 = unknown;

export type CategoriesControllerGetByIdStatus404 = unknown;

export type CategoriesControllerGetByIdOptions = {
	body?: never;
	path: CategoriesControllerGetByIdPath;
	query?: never;
	headers?: never;
};

export type CategoriesControllerGetByIdResponses = {
	"200": CategoriesControllerGetByIdStatus200;
	"401": CategoriesControllerGetByIdStatus401;
	"404": CategoriesControllerGetByIdStatus404;
};

/**
 * @description Union of all possible responses
 */
export type CategoriesControllerGetByIdResponse =
	CategoriesControllerGetByIdStatus200;
