/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CategoryResponseDto } from "../CategoryResponseDto";
import type { CreateCategoryDto } from "../CreateCategoryDto";

export type CategoriesControllerCreateStatus201 = CategoryResponseDto;

export type CategoriesControllerCreateStatus401 = unknown;

export type CategoriesControllerCreateStatus403 = unknown;

export type CategoriesControllerCreateStatus409 = unknown;

export type CategoriesControllerCreateBody = CreateCategoryDto;

export type CategoriesControllerCreateOptions = {
	body: CategoriesControllerCreateBody;
	path?: never;
	query?: never;
	headers?: never;
};

export type CategoriesControllerCreateResponses = {
	"201": CategoriesControllerCreateStatus201;
	"401": CategoriesControllerCreateStatus401;
	"403": CategoriesControllerCreateStatus403;
	"409": CategoriesControllerCreateStatus409;
};

/**
 * @description Union of all possible responses
 */
export type CategoriesControllerCreateResponse =
	CategoriesControllerCreateStatus201;
