/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	BudgetsControllerProgressOptions,
	BudgetsControllerProgressResponses,
} from "../schemas/budgets/BudgetsControllerProgress";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/budgets/:id/progress}
 */
export function budgetsControllerProgress<ThrowOnError extends boolean = true>(
	options: Options<BudgetsControllerProgressOptions, ThrowOnError>,
): Promise<UnwrappedResult<BudgetsControllerProgressResponses, ThrowOnError>> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "GET",
			url: "/v1/budgets/{id}/progress",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<BudgetsControllerProgressResponses, ThrowOnError>
	>;
}
