/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	BudgetsControllerCreateOptions,
	BudgetsControllerCreateResponses,
} from "../schemas/budgets/BudgetsControllerCreate";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/budgets}
 */
export function budgetsControllerCreate<ThrowOnError extends boolean = true>(
	options: Options<BudgetsControllerCreateOptions, ThrowOnError>,
): Promise<UnwrappedResult<BudgetsControllerCreateResponses, ThrowOnError>> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "POST",
			url: "/v1/budgets",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<UnwrappedResult<BudgetsControllerCreateResponses, ThrowOnError>>;
}
