/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	BudgetsControllerGetByIdOptions,
	BudgetsControllerGetByIdResponses,
} from "../schemas/budgets/BudgetsControllerGetById";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/budgets/:id}
 */
export function budgetsControllerGetById<ThrowOnError extends boolean = true>(
	options: Options<BudgetsControllerGetByIdOptions, ThrowOnError>,
): Promise<UnwrappedResult<BudgetsControllerGetByIdResponses, ThrowOnError>> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "GET",
			url: "/v1/budgets/{id}",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<BudgetsControllerGetByIdResponses, ThrowOnError>
	>;
}
