/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	BudgetsControllerReplicateOptions,
	BudgetsControllerReplicateResponses,
} from "../schemas/budgets/BudgetsControllerReplicate";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/budgets}
 */
export function budgetsControllerReplicate<ThrowOnError extends boolean = true>(
	options: Options<BudgetsControllerReplicateOptions, ThrowOnError>,
): Promise<UnwrappedResult<BudgetsControllerReplicateResponses, ThrowOnError>> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "PUT",
			url: "/v1/budgets",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<
		UnwrappedResult<BudgetsControllerReplicateResponses, ThrowOnError>
	>;
}
