/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	BudgetsControllerUpdateOptions,
	BudgetsControllerUpdateResponses,
} from "../schemas/budgets/BudgetsControllerUpdate";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/budgets/:id}
 */
export function budgetsControllerUpdate<ThrowOnError extends boolean = true>(
	options: Options<BudgetsControllerUpdateOptions, ThrowOnError>,
): Promise<UnwrappedResult<BudgetsControllerUpdateResponses, ThrowOnError>> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "PUT",
			url: "/v1/budgets/{id}",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<UnwrappedResult<BudgetsControllerUpdateResponses, ThrowOnError>>;
}
