/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	BudgetsControllerListOptions,
	BudgetsControllerListResponses,
} from "../schemas/budgets/BudgetsControllerList";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/budgets}
 */
export function budgetsControllerList<ThrowOnError extends boolean = true>(
	options: Options<BudgetsControllerListOptions, ThrowOnError> = {},
): Promise<UnwrappedResult<BudgetsControllerListResponses, ThrowOnError>> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "GET",
			url: "/v1/budgets",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<UnwrappedResult<BudgetsControllerListResponses, ThrowOnError>>;
}
