/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	BudgetsControllerRemoveOptions,
	BudgetsControllerRemoveResponses,
} from "../schemas/budgets/BudgetsControllerRemove";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1/budgets/:id}
 */
export function budgetsControllerRemove<ThrowOnError extends boolean = true>(
	options: Options<BudgetsControllerRemoveOptions, ThrowOnError>,
): Promise<UnwrappedResult<BudgetsControllerRemoveResponses, ThrowOnError>> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "DELETE",
			url: "/v1/budgets/{id}",
			security: [{ type: "http", scheme: "bearer" }],
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<UnwrappedResult<BudgetsControllerRemoveResponses, ThrowOnError>>;
}
