/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	BudgetsControllerListOptions,
	BudgetsControllerListStatus200,
} from "../../schemas/budgets/BudgetsControllerList";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { budgetsControllerList } from "../budgetsControllerList";

export const budgetsControllerListQueryKey = ({
	query,
}: Omit<BudgetsControllerListOptions, "headers"> = {}) =>
	[{ url: "/v1/budgets" }, ...(query ? [query] : [])] as const;

type BudgetsControllerListQueryKey = ReturnType<
	typeof budgetsControllerListQueryKey
>;

export function budgetsControllerListQueryOptions(
	{ query }: BudgetsControllerListOptions = {},
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const queryKey = budgetsControllerListQueryKey({ query });
	return queryOptions<
		BudgetsControllerListStatus200,
		ResponseErrorConfig<Error>,
		BudgetsControllerListStatus200,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return await budgetsControllerList({
				...config,
				query,
				signal: config.signal ?? signal,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/budgets}
 */
export function useBudgetsControllerList<
	TData = BudgetsControllerListStatus200,
	TQueryData = BudgetsControllerListStatus200,
	TQueryKey extends QueryKey = BudgetsControllerListQueryKey,
>(
	{
		query,
	}: {
		query?:
			| BudgetsControllerListOptions["query"]
			| (() => BudgetsControllerListOptions["query"]);
	} = {},
	options: {
		query?: Partial<
			QueryObserverOptions<
				BudgetsControllerListStatus200,
				ResponseErrorConfig<Error>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const resolvedParams = {
		query: typeof query === "function" ? query() : query,
	};
	const queryKey =
		resolvedOptions?.queryKey ?? budgetsControllerListQueryKey(resolvedParams);

	const queryResult = useQuery(
		{
			...budgetsControllerListQueryOptions(resolvedParams, config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
		queryKey: TQueryKey;
	};

	queryResult.queryKey = queryKey as TQueryKey;

	return queryResult;
}
