/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	BudgetsControllerCreateOptions,
	BudgetsControllerCreateStatus201,
	BudgetsControllerCreateStatus404,
	BudgetsControllerCreateStatus409,
} from "../../schemas/budgets/BudgetsControllerCreate";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { budgetsControllerCreate } from "../budgetsControllerCreate";

export const budgetsControllerCreateMutationKey = () =>
	[{ url: "/v1/budgets" }] as const;

export function budgetsControllerCreateMutationOptions<TContext = unknown>(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const mutationKey = budgetsControllerCreateMutationKey();
	return mutationOptions<
		BudgetsControllerCreateStatus201,
		ResponseErrorConfig<
			BudgetsControllerCreateStatus404 | BudgetsControllerCreateStatus409
		>,
		BudgetsControllerCreateOptions,
		TContext
	>({
		mutationKey,
		mutationFn: async ({ body }) => {
			return await budgetsControllerCreate({
				...config,
				body,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/budgets}
 */
export function useBudgetsControllerCreate<TContext>(
	options: {
		mutation?: UseMutationOptions<
			BudgetsControllerCreateStatus201,
			ResponseErrorConfig<
				BudgetsControllerCreateStatus404 | BudgetsControllerCreateStatus409
			>,
			BudgetsControllerCreateOptions,
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? budgetsControllerCreateMutationKey();

	const baseOptions = budgetsControllerCreateMutationOptions(
		config,
	) as UseMutationOptions<
		BudgetsControllerCreateStatus201,
		ResponseErrorConfig<
			BudgetsControllerCreateStatus404 | BudgetsControllerCreateStatus409
		>,
		BudgetsControllerCreateOptions,
		TContext
	>;

	return useMutation<
		BudgetsControllerCreateStatus201,
		ResponseErrorConfig<
			BudgetsControllerCreateStatus404 | BudgetsControllerCreateStatus409
		>,
		BudgetsControllerCreateOptions,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		BudgetsControllerCreateStatus201,
		ResponseErrorConfig<
			BudgetsControllerCreateStatus404 | BudgetsControllerCreateStatus409
		>,
		BudgetsControllerCreateOptions,
		TContext
	>;
}
