/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	BudgetsControllerRemoveOptions,
	BudgetsControllerRemoveStatus200,
	BudgetsControllerRemoveStatus409,
} from "../../schemas/budgets/BudgetsControllerRemove";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { budgetsControllerRemove } from "../budgetsControllerRemove";

export const budgetsControllerRemoveMutationKey = () =>
	[{ url: "/v1/budgets/:id" }] as const;

export function budgetsControllerRemoveMutationOptions<TContext = unknown>(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const mutationKey = budgetsControllerRemoveMutationKey();
	return mutationOptions<
		BudgetsControllerRemoveStatus200,
		ResponseErrorConfig<BudgetsControllerRemoveStatus409>,
		BudgetsControllerRemoveOptions,
		TContext
	>({
		mutationKey,
		mutationFn: async ({ path }) => {
			return await budgetsControllerRemove({
				...config,
				path,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/budgets/:id}
 */
export function useBudgetsControllerRemove<TContext>(
	options: {
		mutation?: UseMutationOptions<
			BudgetsControllerRemoveStatus200,
			ResponseErrorConfig<BudgetsControllerRemoveStatus409>,
			BudgetsControllerRemoveOptions,
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? budgetsControllerRemoveMutationKey();

	const baseOptions = budgetsControllerRemoveMutationOptions(
		config,
	) as UseMutationOptions<
		BudgetsControllerRemoveStatus200,
		ResponseErrorConfig<BudgetsControllerRemoveStatus409>,
		BudgetsControllerRemoveOptions,
		TContext
	>;

	return useMutation<
		BudgetsControllerRemoveStatus200,
		ResponseErrorConfig<BudgetsControllerRemoveStatus409>,
		BudgetsControllerRemoveOptions,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		BudgetsControllerRemoveStatus200,
		ResponseErrorConfig<BudgetsControllerRemoveStatus409>,
		BudgetsControllerRemoveOptions,
		TContext
	>;
}
