/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	BudgetsControllerGetByIdOptions,
	BudgetsControllerGetByIdStatus200,
	BudgetsControllerGetByIdStatus404,
} from "../../schemas/budgets/BudgetsControllerGetById";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { budgetsControllerGetById } from "../budgetsControllerGetById";

export const budgetsControllerGetByIdQueryKey = ({
	path,
}: Omit<BudgetsControllerGetByIdOptions, "headers">) =>
	[{ url: "/v1/budgets/:id", params: path }] as const;

type BudgetsControllerGetByIdQueryKey = ReturnType<
	typeof budgetsControllerGetByIdQueryKey
>;

export function budgetsControllerGetByIdQueryOptions(
	{ path }: BudgetsControllerGetByIdOptions,
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const queryKey = budgetsControllerGetByIdQueryKey({ path });
	return queryOptions<
		BudgetsControllerGetByIdStatus200,
		ResponseErrorConfig<BudgetsControllerGetByIdStatus404>,
		BudgetsControllerGetByIdStatus200,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return await budgetsControllerGetById({
				...config,
				path,
				signal: config.signal ?? signal,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/budgets/:id}
 */
export function useBudgetsControllerGetById<
	TData = BudgetsControllerGetByIdStatus200,
	TQueryData = BudgetsControllerGetByIdStatus200,
	TQueryKey extends QueryKey = BudgetsControllerGetByIdQueryKey,
>(
	{
		path,
	}: {
		path:
			| BudgetsControllerGetByIdOptions["path"]
			| (() => BudgetsControllerGetByIdOptions["path"]);
	},
	options: {
		query?: Partial<
			QueryObserverOptions<
				BudgetsControllerGetByIdStatus200,
				ResponseErrorConfig<BudgetsControllerGetByIdStatus404>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const resolvedParams = { path: typeof path === "function" ? path() : path };
	const queryKey =
		resolvedOptions?.queryKey ??
		budgetsControllerGetByIdQueryKey(resolvedParams);

	const queryResult = useQuery(
		{
			...budgetsControllerGetByIdQueryOptions(resolvedParams, config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<
		TData,
		ResponseErrorConfig<BudgetsControllerGetByIdStatus404>
	> & { queryKey: TQueryKey };

	queryResult.queryKey = queryKey as TQueryKey;

	return queryResult;
}
