/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	BudgetsControllerProgressOptions,
	BudgetsControllerProgressStatus200,
} from "../../schemas/budgets/BudgetsControllerProgress";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { budgetsControllerProgress } from "../budgetsControllerProgress";

export const budgetsControllerProgressQueryKey = ({
	path,
}: Omit<BudgetsControllerProgressOptions, "headers">) =>
	[{ url: "/v1/budgets/:id/progress", params: path }] as const;

type BudgetsControllerProgressQueryKey = ReturnType<
	typeof budgetsControllerProgressQueryKey
>;

export function budgetsControllerProgressQueryOptions(
	{ path }: BudgetsControllerProgressOptions,
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const queryKey = budgetsControllerProgressQueryKey({ path });
	return queryOptions<
		BudgetsControllerProgressStatus200,
		ResponseErrorConfig<Error>,
		BudgetsControllerProgressStatus200,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return await budgetsControllerProgress({
				...config,
				path,
				signal: config.signal ?? signal,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/budgets/:id/progress}
 */
export function useBudgetsControllerProgress<
	TData = BudgetsControllerProgressStatus200,
	TQueryData = BudgetsControllerProgressStatus200,
	TQueryKey extends QueryKey = BudgetsControllerProgressQueryKey,
>(
	{
		path,
	}: {
		path:
			| BudgetsControllerProgressOptions["path"]
			| (() => BudgetsControllerProgressOptions["path"]);
	},
	options: {
		query?: Partial<
			QueryObserverOptions<
				BudgetsControllerProgressStatus200,
				ResponseErrorConfig<Error>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const resolvedParams = { path: typeof path === "function" ? path() : path };
	const queryKey =
		resolvedOptions?.queryKey ??
		budgetsControllerProgressQueryKey(resolvedParams);

	const queryResult = useQuery(
		{
			...budgetsControllerProgressQueryOptions(resolvedParams, config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
		queryKey: TQueryKey;
	};

	queryResult.queryKey = queryKey as TQueryKey;

	return queryResult;
}
