/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	BudgetsControllerReplicateOptions,
	BudgetsControllerReplicateStatus200,
} from "../../schemas/budgets/BudgetsControllerReplicate";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { budgetsControllerReplicate } from "../budgetsControllerReplicate";

export const budgetsControllerReplicateMutationKey = () =>
	[{ url: "/v1/budgets" }] as const;

export function budgetsControllerReplicateMutationOptions<TContext = unknown>(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const mutationKey = budgetsControllerReplicateMutationKey();
	return mutationOptions<
		BudgetsControllerReplicateStatus200,
		ResponseErrorConfig<Error>,
		BudgetsControllerReplicateOptions,
		TContext
	>({
		mutationKey,
		mutationFn: async ({ body }) => {
			return await budgetsControllerReplicate({
				...config,
				body,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/budgets}
 */
export function useBudgetsControllerReplicate<TContext>(
	options: {
		mutation?: UseMutationOptions<
			BudgetsControllerReplicateStatus200,
			ResponseErrorConfig<Error>,
			BudgetsControllerReplicateOptions,
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? budgetsControllerReplicateMutationKey();

	const baseOptions = budgetsControllerReplicateMutationOptions(
		config,
	) as UseMutationOptions<
		BudgetsControllerReplicateStatus200,
		ResponseErrorConfig<Error>,
		BudgetsControllerReplicateOptions,
		TContext
	>;

	return useMutation<
		BudgetsControllerReplicateStatus200,
		ResponseErrorConfig<Error>,
		BudgetsControllerReplicateOptions,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		BudgetsControllerReplicateStatus200,
		ResponseErrorConfig<Error>,
		BudgetsControllerReplicateOptions,
		TContext
	>;
}
