/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import type { RequestConfig, ResponseErrorConfig } from "../../.kubb/client";
import type {
	BudgetsControllerUpdateOptions,
	BudgetsControllerUpdateStatus200,
} from "../../schemas/budgets/BudgetsControllerUpdate";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { budgetsControllerUpdate } from "../budgetsControllerUpdate";

export const budgetsControllerUpdateMutationKey = () =>
	[{ url: "/v1/budgets/:id" }] as const;

export function budgetsControllerUpdateMutationOptions<TContext = unknown>(
	config: Partial<
		Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
	> = {},
) {
	const mutationKey = budgetsControllerUpdateMutationKey();
	return mutationOptions<
		BudgetsControllerUpdateStatus200,
		ResponseErrorConfig<Error>,
		BudgetsControllerUpdateOptions,
		TContext
	>({
		mutationKey,
		mutationFn: async ({ path, body }) => {
			return await budgetsControllerUpdate({
				...config,
				path,
				body,
				throwOnError: true,
			});
		},
	});
}

/**
 * {@link /v1/budgets/:id}
 */
export function useBudgetsControllerUpdate<TContext>(
	options: {
		mutation?: UseMutationOptions<
			BudgetsControllerUpdateStatus200,
			ResponseErrorConfig<Error>,
			BudgetsControllerUpdateOptions,
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			Omit<RequestConfig, "path" | "query" | "body" | "headers" | "url">
		>;
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? budgetsControllerUpdateMutationKey();

	const baseOptions = budgetsControllerUpdateMutationOptions(
		config,
	) as UseMutationOptions<
		BudgetsControllerUpdateStatus200,
		ResponseErrorConfig<Error>,
		BudgetsControllerUpdateOptions,
		TContext
	>;

	return useMutation<
		BudgetsControllerUpdateStatus200,
		ResponseErrorConfig<Error>,
		BudgetsControllerUpdateOptions,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		BudgetsControllerUpdateStatus200,
		ResponseErrorConfig<Error>,
		BudgetsControllerUpdateOptions,
		TContext
	>;
}
