/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AttachmentResponseDto = {
	/**
	 * @example uuid-attachment
	 * @type string
	 */
	id: string;
	/**
	 * @example uuid-transaction
	 * @type string
	 */
	transactionId: string;
	/**
	 * @example conta_de_luz.pdf
	 * @type string
	 */
	fileName: string;
	/**
	 * @example application/pdf
	 * @type string
	 */
	mimeType: string;
	/**
	 * @example 214532
	 * @type number
	 */
	sizeBytes: number;
	/**
	 * @description
	 * Format: `date-time`
	 * @example 2026-08-05T12:00:00.000Z
	 * @type string
	 */
	createdAt: string;
};
