/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AttachmentDownloadResponseDto = {
	/**
	 * @type string
	 */
	url: string;
	/**
	 * @type string
	 */
	fileName: string;
};
