/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AttachmentResponseDto = {
	/**
	 * @type string
	 */
	id: string;
	/**
	 * @type string
	 */
	transactionId: string;
	/**
	 * @type string
	 */
	fileName: string;
	/**
	 * @type string
	 */
	mimeType: string;
	/**
	 * @type number
	 */
	sizeBytes: number;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
};
