/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AttachmentDownloadResponseDto = {
	/**
	 * @example https://....r2.cloudflarestorage.com/...
	 * @type string
	 */
	url: string;
	/**
	 * @example conta_de_luz.pdf
	 * @type string
	 */
	fileName: string;
};
