/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type BudgetProgressResponseDto = {
	/**
	 * @example 320.5
	 * @type number
	 */
	current: number;
	/**
	 * @example 500
	 * @type number
	 */
	max: number;
	/**
	 * @example 64.1
	 * @type number
	 */
	percentage: number;
	/**
	 * @example false
	 * @type boolean
	 */
	isOverBudget: boolean;
	/**
	 * @description Transações (ganho ou gasto) da categoria no mês
	 * @example 3
	 * @type number
	 */
	transactionCount: number;
	/**
	 * @example 2026-03
	 * @type string
	 */
	budgetMonth: string;
	/**
	 * @example Alimentação
	 * @type string
	 */
	categoryName: string;
	/**
	 * @example #22C55E
	 * @type string
	 */
	categoryColor: string;
	/**
	 * @description
	 * Format: `date-time`
	 * @type string
	 */
	startDate: string;
	/**
	 * @description
	 * Format: `date-time`
	 * @type string
	 */
	endDate: string;
};
