/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CategoryResponseDto } from "./CategoryResponseDto";

export type BudgetResponseDto = {
	/**
	 * @example uuid-budget
	 * @type string
	 */
	id: string;
	/**
	 * @example uuid-user
	 * @type string
	 */
	userId: string;
	/**
	 * @description Valor decimal como string
	 * @example 500.00
	 * @type string
	 */
	amount: string;
	/**
	 * @description
	 * Format: `date-time`
	 * @type string
	 */
	createdAt: string;
	/**
	 * @description
	 * Format: `date-time`
	 * @type string
	 */
	updatedAt: string;
	/**
	 * @example uuid-category
	 * @type string
	 */
	categoryId: string;
	/**
	 * @example 2026-03
	 * @type string
	 */
	budgetMonth: string;
	/**
	 * @description Presente em list/getById/update; ausente na resposta de create
	 * @type object | undefined
	 */
	category?: CategoryResponseDto;
};
