/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type BudgetProgressResponseDto = {
	/**
	 * @type number
	 */
	current: number;
	/**
	 * @type number
	 */
	max: number;
	/**
	 * @type number
	 */
	percentage: number;
	/**
	 * @type boolean
	 */
	isOverBudget: boolean;
	/**
	 * @description Transações (ganho ou gasto) da categoria no mês
	 * @type number
	 */
	transactionCount: number;
	/**
	 * @type string
	 */
	budgetMonth: string;
	/**
	 * @type string
	 */
	categoryName: string;
	/**
	 * @type string
	 */
	categoryColor: string;
	/**
	 * @type string, date-time
	 */
	startDate: string;
	/**
	 * @type string, date-time
	 */
	endDate: string;
};
