/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CategoryResponseDto } from "./category-response-dto.ts";

export type BudgetResponseDto = {
	/**
	 * @type string
	 */
	id: string;
	/**
	 * @type string
	 */
	userId: string;
	/**
	 * @description Valor decimal como string
	 * @type string
	 */
	amount: string;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
	/**
	 * @type string
	 */
	categoryId: string;
	/**
	 * @type string
	 */
	budgetMonth: string;
	/**
	 * @description Presente em list/getById/update; ausente na resposta de create
	 */
	category?: CategoryResponseDto;
};
