/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const categoryListItemDtoTypeEnum = {
	GANHO: "GANHO",
	GASTO: "GASTO",
	AMBOS: "AMBOS",
} as const;

export type CategoryListItemDtoTypeEnumKey =
	(typeof categoryListItemDtoTypeEnum)[keyof typeof categoryListItemDtoTypeEnum];

export type CategoryListItemDto = {
	/**
	 * @example uuid-category
	 * @type string
	 */
	id: string;
	/**
	 * @example uuid-user
	 * @type string
	 */
	userId: string;
	/**
	 * @example Alimentação
	 * @type string
	 */
	name: string;
	/**
	 * @example #22C55E
	 * @type string
	 */
	color: string;
	/**
	 * @example food
	 * @type string | undefined
	 */
	icon?: string | null;
	/**
	 * @example false
	 * @type boolean
	 */
	isDefault: boolean;
	type?: CategoryListItemDtoTypeEnumKey | null;
	/**
	 * @description
	 * Format: `date-time`
	 * @type string
	 */
	createdAt: string;
	/**
	 * @description
	 * Format: `date-time`
	 * @type string
	 */
	updatedAt: string;
	/**
	 * @description Transações lançadas nesta categoria
	 * @example 4
	 * @type number
	 */
	transactionCount: number;
	/**
	 * @description Orçamentos que usam esta categoria
	 * @example 1
	 * @type number
	 */
	budgetCount: number;
};
