/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const categoryListItemDtoTypeEnum = {
	GANHO: "GANHO",
	GASTO: "GASTO",
	AMBOS: "AMBOS",
} as const;

export type CategoryListItemDtoTypeEnumKey =
	(typeof categoryListItemDtoTypeEnum)[keyof typeof categoryListItemDtoTypeEnum];

export type CategoryListItemDto = {
	/**
	 * @type string
	 */
	id: string;
	/**
	 * @type string
	 */
	userId: string;
	/**
	 * @type string
	 */
	name: string;
	/**
	 * @type string
	 */
	color: string;
	/**
	 * @type string
	 */
	icon?: string | null;
	/**
	 * @type boolean
	 */
	isDefault: boolean;
	/**
	 * @type string
	 */
	type?: CategoryListItemDtoTypeEnumKey | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
	/**
	 * @description Transações lançadas nesta categoria
	 * @type number
	 */
	transactionCount: number;
	/**
	 * @description Orçamentos que usam esta categoria
	 * @type number
	 */
	budgetCount: number;
};
