/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const categoryResponseDtoTypeEnum = {
	GANHO: "GANHO",
	GASTO: "GASTO",
	AMBOS: "AMBOS",
} as const;

export type CategoryResponseDtoTypeEnumKey =
	(typeof categoryResponseDtoTypeEnum)[keyof typeof categoryResponseDtoTypeEnum];

export type CategoryResponseDto = {
	/**
	 * @type string
	 */
	id: string;
	/**
	 * @type string
	 */
	userId: string;
	/**
	 * @type string
	 */
	name: string;
	/**
	 * @type string
	 */
	color: string;
	/**
	 * @type string
	 */
	icon?: string | null;
	/**
	 * @type boolean
	 */
	isDefault: boolean;
	/**
	 * @type string
	 */
	type?: CategoryResponseDtoTypeEnumKey | null;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};
