/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const categoryResponseDtoTypeEnum = {
	GANHO: "GANHO",
	GASTO: "GASTO",
	AMBOS: "AMBOS",
} as const;

export type CategoryResponseDtoTypeEnumKey =
	(typeof categoryResponseDtoTypeEnum)[keyof typeof categoryResponseDtoTypeEnum];

export type CategoryResponseDto = {
	/**
	 * @example uuid-category
	 * @type string
	 */
	id: string;
	/**
	 * @example uuid-user
	 * @type string
	 */
	userId: string;
	/**
	 * @example Alimentação
	 * @type string
	 */
	name: string;
	/**
	 * @example #22C55E
	 * @type string
	 */
	color: string;
	/**
	 * @example food
	 * @type string | undefined
	 */
	icon?: string | null;
	/**
	 * @example false
	 * @type boolean
	 */
	isDefault: boolean;
	type?: CategoryResponseDtoTypeEnumKey | null;
	/**
	 * @description
	 * Format: `date-time`
	 * @type string
	 */
	createdAt: string;
	/**
	 * @description
	 * Format: `date-time`
	 * @type string
	 */
	updatedAt: string;
};
