/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateBudgetDto = {
	/**
	 * @example 1200.5
	 * @type number
	 */
	amount: number;
	/**
	 * @example 2026-03
	 * @type string
	 */
	budgetMonth: string;
	/**
	 * @example uuid-category
	 * @type string
	 */
	categoryId: string;
};
