/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const createTransactionDtoTypeEnum = {
	GANHO: "GANHO",
	GASTO: "GASTO",
} as const;

export type CreateTransactionDtoTypeEnumKey =
	(typeof createTransactionDtoTypeEnum)[keyof typeof createTransactionDtoTypeEnum];

export const createTransactionDtoTagEnum = {
	FALTA: "FALTA",
	PAGO: "PAGO",
	DEVOLVER: "DEVOLVER",
	ECONOMIA: "ECONOMIA",
	RECEBIDO: "RECEBIDO",
} as const;

export type CreateTransactionDtoTagEnumKey =
	(typeof createTransactionDtoTagEnum)[keyof typeof createTransactionDtoTagEnum];

export const createTransactionDtoPaymentMethodEnum = {
	PIX: "PIX",
	DEBITO: "DEBITO",
	CREDITO: "CREDITO",
} as const;

export type CreateTransactionDtoPaymentMethodEnumKey =
	(typeof createTransactionDtoPaymentMethodEnum)[keyof typeof createTransactionDtoPaymentMethodEnum];

export type CreateTransactionDto = {
	/**
	 * @example Supermercado
	 * @type string
	 */
	description: string;
	/**
	 * @example 145.9
	 * @type number
	 */
	amount: number;
	/**
	 * @example 2026-03-31T00:00:00.000Z
	 * @type string
	 */
	date: string;
	/**
	 * @example GASTO
	 * @type string
	 */
	type: CreateTransactionDtoTypeEnumKey;
	/**
	 * @example uuid-category
	 * @type string
	 */
	categoryId: string;
	/**
	 * @example Compra mensal
	 * @type string | undefined
	 */
	notes?: string;
	tag?: CreateTransactionDtoTagEnumKey | null;
	paymentMethod?: CreateTransactionDtoPaymentMethodEnumKey | null;
	/**
	 * @minLength 2
	 * @maxLength 12
	 * @example 3
	 * @type number | undefined
	 */
	installmentCount?: number;
};
