/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DashboardBudgetProgressDto } from "./DashboardBudgetProgressDto";
import type { DashboardExpenseByCategoryDto } from "./DashboardExpenseByCategoryDto";
import type { DashboardMonthlyDataDto } from "./DashboardMonthlyDataDto";
import type { DashboardSummaryDto } from "./DashboardSummaryDto";
import type { TransactionResponseDto } from "./TransactionResponseDto";

export type DashboardResponseDto = {
	summary: DashboardSummaryDto;
	expensesByCategory: DashboardExpenseByCategoryDto[];
	recentTransactions: TransactionResponseDto[];
	budgets: DashboardBudgetProgressDto[];
	/**
	 * @description Últimos 6 meses
	 * @type array
	 */
	monthlyData: DashboardMonthlyDataDto[];
};
