/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DashboardMonthlyDataDto = {
	/**
	 * @type string
	 */
	month: string;
	/**
	 * @type number
	 */
	income: number;
	/**
	 * @type number
	 */
	expenses: number;
	/**
	 * @type number
	 */
	savings: number;
};
