/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DashboardExpenseByCategoryDto = {
	/**
	 * @example Alimentação
	 * @type string
	 */
	name: string;
	/**
	 * @example 540.9
	 * @type number
	 */
	value: number;
	/**
	 * @example #22C55E
	 * @type string
	 */
	color: string;
};
