/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DashboardMonthlyDataDto = {
	/**
	 * @example mar
	 * @type string
	 */
	month: string;
	/**
	 * @example 4200.5
	 * @type number
	 */
	income: number;
	/**
	 * @example 2600.25
	 * @type number
	 */
	expenses: number;
	/**
	 * @example 1600.25
	 * @type number
	 */
	savings: number;
};
