/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DashboardStatDto } from "./DashboardStatDto";

export type DashboardSummaryDto = {
	income: DashboardStatDto;
	expenses: DashboardStatDto;
	savings: DashboardStatDto;
	/**
	 * @example 1800.25
	 * @type number
	 */
	balance: number;
};
