/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DashboardBudgetProgressDto } from "./dashboard-budget-progress-dto.ts";
import type { DashboardExpenseByCategoryDto } from "./dashboard-expense-by-category-dto.ts";
import type { DashboardMonthlyDataDto } from "./dashboard-monthly-data-dto.ts";
import type { DashboardSummaryDto } from "./dashboard-summary-dto.ts";
import type { TransactionResponseDto } from "./transaction-response-dto.ts";

export type DashboardResponseDto = {
	/**
	 * @type object
	 */
	summary: DashboardSummaryDto;
	/**
	 * @type array
	 */
	expensesByCategory: DashboardExpenseByCategoryDto[];
	/**
	 * @type array
	 */
	recentTransactions: TransactionResponseDto[];
	/**
	 * @type array
	 */
	budgets: DashboardBudgetProgressDto[];
	/**
	 * @description Últimos 6 meses
	 * @type array
	 */
	monthlyData: DashboardMonthlyDataDto[];
};
