/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DashboardExpenseByCategoryDto = {
	/**
	 * @type string
	 */
	name: string;
	/**
	 * @type number
	 */
	value: number;
	/**
	 * @type string
	 */
	color: string;
};
