/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DashboardBudgetProgressDto = {
	/**
	 * @type string
	 */
	id: string;
	/**
	 * @description Nome da categoria
	 * @type string
	 */
	category: string;
	/**
	 * @type number
	 */
	current: number;
	/**
	 * @type number
	 */
	max: number;
	/**
	 * @type string
	 */
	color: string;
};
