/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DashboardStatDto = {
	/**
	 * @example 4200.5
	 * @type number
	 */
	amount: number;
	/**
	 * @description Variação percentual vs. mês anterior
	 * @example 12.4
	 * @type number
	 */
	change: number;
};
