/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DashboardStatDto } from "./dashboard-stat-dto.ts";

export type DashboardSummaryDto = {
	/**
	 * @type object
	 */
	income: DashboardStatDto;
	/**
	 * @type object
	 */
	expenses: DashboardStatDto;
	/**
	 * @type object
	 */
	savings: DashboardStatDto;
	/**
	 * @type number
	 */
	balance: number;
};
