/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ForgotPasswordResponseDto = {
	/**
	 * @type string
	 */
	message: string;
	/**
	 * @description Só presente fora de produção, pra facilitar testes locais
	 * @type string | undefined
	 */
	resetToken?: string;
};
