/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UserResponseDto } from "./user-response-dto.ts";

export type ListUsersResponseDto = {
	/**
	 * @type array
	 */
	items: UserResponseDto[];
	/**
	 * @type number
	 */
	page: number;
	/**
	 * @type number
	 */
	perPage: number;
	/**
	 * @type number
	 */
	total: number;
	/**
	 * @type number
	 */
	totalPages: number;
};
