/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UserResponseDto } from "./UserResponseDto";

export type ListUsersResponseDto = {
	items: UserResponseDto[];
	/**
	 * @example 1
	 * @type number
	 */
	page: number;
	/**
	 * @example 20
	 * @type number
	 */
	perPage: number;
	/**
	 * @example 3
	 * @type number
	 */
	total: number;
	/**
	 * @example 1
	 * @type number
	 */
	totalPages: number;
};
