/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type LoginDto = {
	/**
	 * @example admin@rfinance.local
	 * @type string
	 */
	email: string;
	/**
	 * @example Admin@123
	 * @type string
	 */
	password: string;
};
