/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UserSummaryDto } from "./user-summary-dto.ts";

export type MeResponseDto = {
	/**
	 * @type object
	 */
	user: UserSummaryDto;
};
