/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MeUserDto } from "./me-user-dto.ts";

export type MeResponseDto = {
	/**
	 * @type object
	 */
	user: MeUserDto;
};
