/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const meUserDtoRoleEnum = {
	ADMIN: "ADMIN",
	USER: "USER",
} as const;

export type MeUserDtoRoleEnumKey =
	(typeof meUserDtoRoleEnum)[keyof typeof meUserDtoRoleEnum];

export type MeUserDto = {
	/**
	 * @type string
	 */
	id: string;
	/**
	 * @type string
	 */
	name: string;
	/**
	 * @type string
	 */
	email: string;
	/**
	 * @type string
	 */
	role: MeUserDtoRoleEnumKey;
	/**
	 * @type string, date-time
	 */
	privacyAcceptedAt: string | null;
	/**
	 * @type string
	 */
	privacyPolicyVersion: string | null;
};
