/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type MessageResponseDto = {
	/**
	 * @example Operação realizada com sucesso
	 * @type string
	 */
	message: string;
};
