/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const meUserDtoRoleEnum = {
	ADMIN: "ADMIN",
	USER: "USER",
} as const;

export type MeUserDtoRoleEnumKey =
	(typeof meUserDtoRoleEnum)[keyof typeof meUserDtoRoleEnum];

export type MeUserDto = {
	/**
	 * @example uuid-user
	 * @type string
	 */
	id: string;
	/**
	 * @example Administrador
	 * @type string
	 */
	name: string;
	/**
	 * @example admin@rfinance.local
	 * @type string
	 */
	email: string;
	/**
	 * @example ADMIN
	 * @type string
	 */
	role: MeUserDtoRoleEnumKey;
	/**
	 * @description
	 * Format: `date-time`
	 * @type string
	 */
	privacyAcceptedAt: string | null;
	privacyPolicyVersion: string | null;
	/**
	 * @description
	 * Format: `date-time`
	 * @type string
	 */
	createdAt: string;
};
