/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type RegisterDto = {
	/**
	 * @example Maria Silva
	 * @type string
	 */
	name: string;
	/**
	 * @example maria@email.com
	 * @type string
	 */
	email: string;
	/**
	 * @example Senha@123
	 * @type string
	 */
	password: string;
};
