/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ReplicateBudgetsDto = {
	/**
	 * @example replicate
	 * @type string
	 */
	action: string;
	/**
	 * @example 2026-04
	 * @type string
	 */
	targetMonth: string;
};
