/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BudgetResponseDto } from "./budget-response-dto.ts";

export type ReplicateBudgetsResponseDto = {
	/**
	 * @type string
	 */
	message: string;
	/**
	 * @type array
	 */
	budgets: BudgetResponseDto[];
};
