/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BudgetResponseDto } from "./BudgetResponseDto";

export type ReplicateBudgetsResponseDto = {
	/**
	 * @example 3 orçamentos replicados com sucesso
	 * @type string
	 */
	message: string;
	budgets: BudgetResponseDto[];
};
