/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ResetPasswordDto = {
	/**
	 * @example plain-text-recovery-token
	 * @type string
	 */
	token: string;
	/**
	 * @example NovaSenha@123
	 * @type string
	 */
	password: string;
};
