/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TransactionResponseDto } from "./transaction-response-dto.ts";

export type TransactionListResponseDto = {
	/**
	 * @type array
	 */
	transactions: TransactionResponseDto[];
};
