/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CategoryResponseDto } from "./CategoryResponseDto";

export const transactionResponseDtoTypeEnum = {
	GANHO: "GANHO",
	GASTO: "GASTO",
} as const;

export type TransactionResponseDtoTypeEnumKey =
	(typeof transactionResponseDtoTypeEnum)[keyof typeof transactionResponseDtoTypeEnum];

export const transactionResponseDtoTagEnum = {
	FALTA: "FALTA",
	PAGO: "PAGO",
	DEVOLVER: "DEVOLVER",
	ECONOMIA: "ECONOMIA",
	RECEBIDO: "RECEBIDO",
} as const;

export type TransactionResponseDtoTagEnumKey =
	(typeof transactionResponseDtoTagEnum)[keyof typeof transactionResponseDtoTagEnum];

export const transactionResponseDtoPaymentMethodEnum = {
	PIX: "PIX",
	DEBITO: "DEBITO",
	CREDITO: "CREDITO",
} as const;

export type TransactionResponseDtoPaymentMethodEnumKey =
	(typeof transactionResponseDtoPaymentMethodEnum)[keyof typeof transactionResponseDtoPaymentMethodEnum];

export type TransactionResponseDto = {
	/**
	 * @example uuid-transaction
	 * @type string
	 */
	id: string;
	/**
	 * @example uuid-user
	 * @type string
	 */
	userId: string;
	/**
	 * @example Supermercado
	 * @type string
	 */
	description: string;
	/**
	 * @description Valor decimal como string
	 * @example 145.90
	 * @type string
	 */
	amount: string;
	/**
	 * @description
	 * Format: `date-time`
	 * @example 2026-03-31T00:00:00.000Z
	 * @type string
	 */
	date: string;
	/**
	 * @example Compra mensal
	 * @type string | undefined
	 */
	notes?: string | null;
	/**
	 * @example GASTO
	 * @type string
	 */
	type: TransactionResponseDtoTypeEnumKey;
	/**
	 * @description
	 * Format: `date-time`
	 * @type string
	 */
	createdAt: string;
	/**
	 * @description
	 * Format: `date-time`
	 * @type string
	 */
	updatedAt: string;
	/**
	 * @example uuid-category
	 * @type string
	 */
	categoryId: string;
	tag?: TransactionResponseDtoTagEnumKey | null;
	paymentMethod?: TransactionResponseDtoPaymentMethodEnumKey | null;
	/**
	 * @description Preenchido quando parte de um parcelamento
	 * @type string | undefined
	 */
	installmentGroupId?: string | null;
	installmentIndex?: number | null;
	installmentCount?: number | null;
	category: CategoryResponseDto;
};
