/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TransactionResponseDto } from "./TransactionResponseDto";

export type TransactionListResponseDto = {
	transactions: TransactionResponseDto[];
};
