/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CategoryResponseDto } from "./category-response-dto.ts";

export const transactionResponseDtoTypeEnum = {
	GANHO: "GANHO",
	GASTO: "GASTO",
} as const;

export type TransactionResponseDtoTypeEnumKey =
	(typeof transactionResponseDtoTypeEnum)[keyof typeof transactionResponseDtoTypeEnum];

export const transactionResponseDtoTagEnum = {
	FALTA: "FALTA",
	PAGO: "PAGO",
	DEVOLVER: "DEVOLVER",
	ECONOMIA: "ECONOMIA",
	RECEBIDO: "RECEBIDO",
} as const;

export type TransactionResponseDtoTagEnumKey =
	(typeof transactionResponseDtoTagEnum)[keyof typeof transactionResponseDtoTagEnum];

export const transactionResponseDtoPaymentMethodEnum = {
	PIX: "PIX",
	DEBITO: "DEBITO",
	CREDITO: "CREDITO",
} as const;

export type TransactionResponseDtoPaymentMethodEnumKey =
	(typeof transactionResponseDtoPaymentMethodEnum)[keyof typeof transactionResponseDtoPaymentMethodEnum];

export type TransactionResponseDto = {
	/**
	 * @type string
	 */
	id: string;
	/**
	 * @type string
	 */
	userId: string;
	/**
	 * @type string
	 */
	description: string;
	/**
	 * @description Valor decimal como string
	 * @type string
	 */
	amount: string;
	/**
	 * @type string, date-time
	 */
	date: string;
	/**
	 * @type string
	 */
	notes?: string | null;
	/**
	 * @type string
	 */
	type: TransactionResponseDtoTypeEnumKey;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
	/**
	 * @type string
	 */
	categoryId: string;
	/**
	 * @type string
	 */
	tag?: TransactionResponseDtoTagEnumKey | null;
	/**
	 * @type string
	 */
	paymentMethod?: TransactionResponseDtoPaymentMethodEnumKey | null;
	/**
	 * @description Preenchido quando parte de um parcelamento
	 * @type string
	 */
	installmentGroupId?: string | null;
	/**
	 * @type number
	 */
	installmentIndex?: number | null;
	/**
	 * @type number
	 */
	installmentCount?: number | null;
	/**
	 * @type object
	 */
	category: CategoryResponseDto;
};
