/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateBudgetDto = {
	/**
	 * @example 1200.5
	 * @type number | undefined
	 */
	amount?: number;
	/**
	 * @example 2026-03
	 * @type string | undefined
	 */
	budgetMonth?: string;
	/**
	 * @example uuid-category
	 * @type string | undefined
	 */
	categoryId?: string;
};
