/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const updateUserByAdminDtoRoleEnum = {
	ADMIN: "ADMIN",
	USER: "USER",
} as const;

export type UpdateUserByAdminDtoRoleEnumKey =
	(typeof updateUserByAdminDtoRoleEnum)[keyof typeof updateUserByAdminDtoRoleEnum];

export type UpdateUserByAdminDto = {
	/**
	 * @example Maria Silva
	 * @type string | undefined
	 */
	name?: string;
	/**
	 * @example maria@rfinance.local
	 * @type string | undefined
	 */
	email?: string;
	/**
	 * @example USER
	 * @type string | undefined
	 */
	role?: UpdateUserByAdminDtoRoleEnumKey;
};
