/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateOwnProfileDto = {
	/**
	 * @example Maria Silva
	 * @type string | undefined
	 */
	name?: string;
	/**
	 * @example maria@rfinance.local
	 * @type string | undefined
	 */
	email?: string;
};
