/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const userSummaryDtoRoleEnum = {
	ADMIN: "ADMIN",
	USER: "USER",
} as const;

export type UserSummaryDtoRoleEnumKey =
	(typeof userSummaryDtoRoleEnum)[keyof typeof userSummaryDtoRoleEnum];

export type UserSummaryDto = {
	/**
	 * @example uuid-user
	 * @type string
	 */
	id: string;
	/**
	 * @example Administrador
	 * @type string
	 */
	name: string;
	/**
	 * @example admin@rfinance.local
	 * @type string
	 */
	email: string;
	/**
	 * @example ADMIN
	 * @type string
	 */
	role: UserSummaryDtoRoleEnumKey;
};
