/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const userResponseDtoRoleEnum = {
	ADMIN: "ADMIN",
	USER: "USER",
} as const;

export type UserResponseDtoRoleEnumKey =
	(typeof userResponseDtoRoleEnum)[keyof typeof userResponseDtoRoleEnum];

export type UserResponseDto = {
	/**
	 * @type string
	 */
	id: string;
	/**
	 * @type string
	 */
	name: string;
	/**
	 * @type string
	 */
	email: string;
	/**
	 * @type string
	 */
	role: UserResponseDtoRoleEnumKey;
	/**
	 * @type string, date-time
	 */
	createdAt: string;
	/**
	 * @type string, date-time
	 */
	updatedAt: string;
};
