/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const userResponseDtoRoleEnum = {
	ADMIN: "ADMIN",
	USER: "USER",
} as const;

export type UserResponseDtoRoleEnumKey =
	(typeof userResponseDtoRoleEnum)[keyof typeof userResponseDtoRoleEnum];

export type UserResponseDto = {
	/**
	 * @example uuid-user
	 * @type string
	 */
	id: string;
	/**
	 * @example Administrador
	 * @type string
	 */
	name: string;
	/**
	 * @example admin@rfinance.local
	 * @type string
	 */
	email: string;
	/**
	 * @example ADMIN
	 * @type string
	 */
	role: UserResponseDtoRoleEnumKey;
	/**
	 * @description
	 * Format: `date-time`
	 * @type string
	 */
	createdAt: string;
	/**
	 * @description
	 * Format: `date-time`
	 * @type string
	 */
	updatedAt: string;
};
