/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Options, UnwrappedResult } from "../.kubb/client";
import type {
	AppControllerGetHealthOptions,
	AppControllerGetHealthResponses,
} from "../schemas/health/AppControllerGetHealth";
import { client, unwrapResult } from "../.kubb/client";

/**
 * {@link /v1}
 */
export function appControllerGetHealth<ThrowOnError extends boolean = true>(
	options: Options<AppControllerGetHealthOptions, ThrowOnError> = {},
): Promise<UnwrappedResult<AppControllerGetHealthResponses, ThrowOnError>> {
	const { client: request = client, ...config } = options;

	return unwrapResult(
		request({
			method: "GET",
			url: "/v1",
			...config,
			throwOnError: config.throwOnError ?? true,
		}),
		config.throwOnError ?? true,
	) as Promise<UnwrappedResult<AppControllerGetHealthResponses, ThrowOnError>>;
}
